/**
 * Additional case studies merged into seed (see seed.ts).
 * filteringCategory uses lowercase "startups" | "enterprises" for listByCategory queries.
 */
export const MISSING_CASE_STUDIES_SEED = [
  {
    name: "002 Sponsorships",
    slug: "002-sponsorships",
    archived: false,
    draft: false,
    filteringCategory: "startups",
    businessType: "Startup",
    productType: "Marketplace app",
    timeline: "2 months",
    keyResults:
      "A custom 2-sided marketplace platform with custom database search filters and in-app messaging",
    sortOrder: 16,
    companyUrl: "https://002sponsorships.com/?stay=yes",
    thumbnailSummary:
      "How 002 Sponsorships became the first-to-market pickleball influencer marketplace",
    thumbnailImage:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/65fdd0fb266484ecf1724e39_002%20Sponsorships_no-code-app-airdev%20(1).jpg",
    customerLogo:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/65fdcdfe6a0b634b6b6d1e7a_Screenshot%202024-03-22%20at%2011.27.42%20AM.png",
    heroSummary: `<p id="">The world's first pickleball influencer marketplace platform 002 Sponsorships is on a mission to simplify brand-influencer collaborations in the rapidly growing pickleball space.</p><p id="">Co-founded by serial entrepreneur Ed Chao, the idea stemmed from the absence of a centralized database for connecting brands breaking into the pickleball space with influencers.</p><p id="">As Chao explains, "We recognized that matching brands with influencers is just something that would help the entire ecosystem as the industry grows."</p><p id="">Seeking a quick entry into the market and leveraging his successful previous collaboration with Airdev on a SportsTech startup platform (<a id="" href="https://www.airdev.co/case-studies/cerebro-sports-analytics-platform-no-code" target="_blank">Cerebro Sports</a>, which got investment from entrepreneur and NBA governor Mark Cuban), Chao turned to the agency once again. Together, they built the 002 Sponsorships platform, enabling fast development and continued iteration of their proof of concept.</p><p id="">With Airdev's help, Chao was able to:</p><ul id=""><li id="">Develop a custom 2-sided marketplace platform with custom database search filters and in-app messaging – built and in-market within 2 months</li><li id="">Sign up 60+ influencer and brands within 2 months of launching</li></ul>`,
    quoteImage:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/64ecef0fc2aaa629ab933cef_Ed%20Chao_Cerebro%20Sport.jpeg",
    quote:
      "\u201cAfter working with Airdev to build Cerebro Sport\u2019s platform, I had 100% confidence in their scoping process and the way they handle pricing. I knew that once all app details were mapped out and wireframes were mocked up that\u2019s exactly what I was going to get \u2013 and we were going to stay within budget and timeline.\u201d",
    quoteName: "Ed Chao",
    quoteRole: "Co-founder of 002 Sponsorships",
    objective: `<p id="">Chao and his team recognized the need for an influencer marketplace platform to support the industry's expansion after running a pickleball stats company called 002 Stats.\u00a0</p><p id=""><em id="">\u201cWe wanted to come up with a very simple proof of concept. We wanted to be first to market. We also wanted to launch something very basic that would enable brand-influencer relationships so we could learn what people want and start facilitating that on both sides of the marketplace.\u201d - Chao</em>\u200d</p>`,
    solution: `<p id="">To develop a working platform that they could quickly evolve with user feedback, 002 Sponsorships turned to Airdev to build everything it needed to launch. Chao's previous experience partnering with Airdev to build a platform showed him that they could quickly develop a robust, legitimate web app at a very affordable cost.</p><p id=""><em id="">"After working with Airdev to build Cerebro Sport's platform, I had 100% confidence in their scoping process and the way they handle pricing. I knew that once all app details were mapped out and wireframes were mocked up that's exactly what I was going to get \u2013 and we were going to stay within budget and timeline." - Chao</em></p><p id="">To translate 002 Sponsorship's vision into detailed product specifications, Airdev's dedicated project manager started by learning about the functionality requirements for the marketplace platform.<em id="">\u200d</em></p><p id="">On the influencer side, 002 Sponsorships needed users to be able to easily create personal profiles to showcase themselves to brands (including DUPR skill ratings, social media metrics, geography, sponsorship history, etc.). On the brand side, the goal was to make it easier for companies to sift through a growing pool of influencers and engage with them to find the right fit for collaborations.<em id="">\u200d</em></p><p id="">Using this information, Airdev's project manager developed a thorough scoping document outlining the exact features and architecture for the app, which a UX designer then converted into high-fidelity mockups to show exactly what users will see when interacting with the product.</p><p id="">This all served as the blueprint for Airdev's development team to quickly and accurately build out and test the app.</p>`,
    result: `<p id="">After a 2-week build timeline, Airdev's development team created a fully functioning marketplace platform that facilitated the complete signup, search, and messaging flow 002 Sponsorships needed to launch and validate their concept with real influencers and brands.</p><p id="">Influencers could build personal profiles, as well as search, filter, and start conversations with brand sponsors in the system. Similarly, brands could quickly sift through and bookmark influencers based on specified criteria then message them via in-app chat.</p><p id="">After launching, 002 Sponsorships used Airdev's Maintenance Mode support plan for a month to address user feedback and make quick iterations. Within just 2 months, the platform has attracted over 60 influencers and brands, with future plans to add more features as the platform expands.</p>`,
    marketplace: false,
    saas: false,
    metaTitle: "002 Sponsorships Pickleball Marketplace",
    publishedOn: "Thu Apr 09 2026 01:52:50 GMT+0000 (Coordinated Universal Time)",
    updatedOn: "Thu Apr 09 2026 01:36:00 GMT+0000 (Coordinated Universal Time)",
  },
  {
    name: "CampHire",
    slug: "camphire",
    archived: false,
    draft: false,
    filteringCategory: "startups",
    businessType: "SMB",
    productType: "Marketplace platform",
    timeline: "3 months",
    keyResults:
      "30+ camp and 250+ candidate sign ups in just 1 month since launch",
    sortOrder: 13,
    companyUrl: "https://www.camphiremarketplace.com/",
    thumbnailSummary:
      "How Airdev helped CampHire automate their recruitment agency via a self-service marketplace platform",
    thumbnailImage:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/6643d6a3fe39d1c4c0867361_CampHire-Airdev-No-Code-App-Example.jpg",
    customerLogo:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/6643d78a8798d8501e30f8f1_CampHire-logo.jpeg",
    heroSummary: `<p id="">CampHire founders Aaron Lyon and Esther Eisenhard needed a way to scale their agency specializing in seasonal staff recruitment for summer camps by the next season.</p><p id="">As Lyon explains, "After years of manually sharing candidate information via email, we decided to invest in a marketplace-style platform where users can self-serve, filter candidates, and make connections automatically. We both have other full-time jobs, so we needed something that didn't require a human to do everything."</p><p id="">To meet their launch deadline, CampHire sought a fast, cost-effective development solution. Lyon explored building the marketplace himself, but decided to partner with Airdev to ensure a timely launch.</p><p id="">With the help of Airdev, CampHire was able to:</p><ul id=""><li id="">Develop an automated 2-sided marketplace platform with custom candidate search filters and reservation and waitlist features for camps</li><li id="">Sign up 30+ camp and 250+ candidate in just 1 month after the launch</li><li id="">Process 200 platform actions/week, including camps reserving, interviewing, releasing, and hiring candidates</li></ul>`,
    quoteImage:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/6643d724fdb365f7820260c8_Aaron%20Lyon_CampHire_Airdev.jpeg",
    quote: `"My first interaction with Airdev started with an exploratory call. I first needed to learn more about their development approach. The sales representative did a good job of stepping back from Airdev entirely and just talking to me about why their approach might be a good solution for us, including all the pros and cons along the way."`,
    quoteName: "Aaron Lyon",
    quoteRole: "Co-founder of CampHire",
    objective: `<p id="">The CampHire founders' goal was to grow their business by offering a self-service client interface for camps looking to hire seasonal staff. But for this to happen, they needed to rapidly develop a high-quality platform that could handle hundreds of users on day 1.</p><p id=""><em id="">"I initially considered hiring a developer to build from scratch, but found that costly and risky. Then I wondered if I could build it myself. That's when I started looking for a development partner who could help me build fast." - Lyon</em>\u200d</p>`,
    solution: `<p id="">Lyon came across Airdev and saw they had experience in similar projects to CampHire's. But he first wanted to make sure Airdev's approach was suitable for his marketplace.</p><p id=""><em id="">"My first interaction with Airdev started with an exploratory call. I first needed to learn more about their development approach. The sales representative did a good job of stepping back from Airdev entirely and just talking to me about why their approach might be a good solution for us, including all the pros and cons along the way." - Lyon</em>\u200d</p><p id="">Following the conversation, Lyon concluded that Airdev could get him the desired outcome quickly and cost-effectively. He also felt confident that Airdev would be a good partner to build with.</p><p id=""><em id="">"I chose Airdev because I needed a team that could educate me throughout the process. They've worked on many different products, and I needed experts that know development inside and out. Plus, their portfolio was impressive, with experience across hundreds of different projects." - Lyon</em>\u200d</p><p id="">CampHire began working with Airdev. Airdev's project manager collaborated closely with Lyon and his sister to develop detailed scoping documents, outlining all build features, logic, and timeline. This included providing strategic recommendations around the platform's core feature, candidate reservations.</p><p id=""><em id="">"Airdev's project manager helped us refine the core reservation logic of the app. We had to figure out what it meant when a camp takes a candidate out of the hiring pool, including how long reservations last and what privileges they get. They also suggested adding a waitlist feature to keep the marketplace looking full and active. Airdev's input was crucial in shaping many of the platform's custom features \u2013 they were great strategic partners." - Lyon</em>\u200d</p><p id="">By ironing out all of the details early on, Airdev's development team had a clear blueprint to quickly and accurately build CampHire's marketplace in the way that they envisioned.</p>`,
    result: `<p id="">With Airdev's help, CampHire's marketplace went live with immediate users on the set deadline. In just 1 month, they signed up 30 camps to recruit seasonal staff on the platform, and added over 250 pre-screened candidate profiles. So far, they're seeing 200 platform actions per week, including camps reserving, interviewing, releasing, and hiring candidates.</p><p id=""><em id="">"The app's launch has been a big success. For the first time in 5 years, my sister and I are hands-off, simply observing as camps sign up, pay, navigate, and hire staff independently. Previously, we spent hours nightly managing client interactions and candidate sharing. Now, it's 100% automated." - Lyon</em>\u200d</p>`,
    marketplace: false,
    saas: false,
    metaTitle: "CampHire Automated Recruiting Market",
    publishedOn: "Thu Apr 09 2026 01:52:50 GMT+0000 (Coordinated Universal Time)",
    updatedOn: "Thu Apr 09 2026 01:33:48 GMT+0000 (Coordinated Universal Time)",
  },
  {
    name: "Consenna & HP for Education",
    slug: "consenna-hp-for-education-marketplace-no-code",
    archived: false,
    draft: false,
    filteringCategory: "enterprises",
    businessType: "Enterprise",
    productType: "Custom marketplace",
    timeline: "3 months",
    keyResults: "30k schools served",
    sortOrder: 2,
    thumbnailSummary:
      "How Airdev helped the consultancy Consenna build a custom marketplace for HP for Education to serve 30k schools across the UK",
    thumbnailImage:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/635076a5905dd76065955f2c_hp-s%20(1).png",
    heroSummary: `<p id="">Consenna is a UK-based consultancy working with global tech manufacturers to design and deploy promotional campaigns.\u00a0</p><p id="">HP hired Consenna to support a program it runs to help schools get credit when trading up old equipment. This program, HP for Education, requires tight coordination between lots of different groups (i.e. schools, resellers, service providers, etc.).\u00a0</p><p id="">To manage activities between these groups and meet its deadline, Consenna partnered with Airdev to build a custom marketplace solution to save time and money, and to create the best experience for schools \u2013 in only 3 months.\u00a0</p><p id="">With Airdev\u2019s help, Consenna was able to:</p><ul id=""><li id="">Develop a multi-sided marketplace coordinating efforts between schools, resellers, service providers, and administrators\u00a0\u00a0</li><li id="">Deploy a tool offered to 30k schools across the UK\u00a0</li><li id="">Win additional work from HP</li></ul>`,
    quoteImage:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/633f107ba16b3b08079c002d_Douglas-Jeffrey.jpeg",
    quote:
      "\u201cWe pride ourselves on going the extra mile, and having to rely on developers to deliver was incredibly stressful to us in the past. Taking a project like this that used to take us 6 months, and being able to launch in 6 weeks has been invaluable to us and our clients.\u201d",
    quoteName: "Douglas Jeffrey",
    quoteRole: "Chairman at Consenna",
    objective: `<p id="">As a consultancy, Consenna needed to work fast and deliver its commitments on-budget and on-time. With a 3-month runway to launch, the team needed a custom solution that met the following objectives:</p><ul id=""><li>Highly functional, managing a complex 4-sided program architecture</li><li>Sleek and intuitive, eliminating friction in school participation</li><li>Scalable and designed to serve 30k+ schools across the UK and Ireland</li></ul><p id="">Consenna couldn\u2019t risk burning its budget and time building a custom platform that didn\u2019t meet HP\u2019s very specific functional requirements, which included:\u00a0</p><ul id=""><li>Intuitive school onboarding and equipment trade-in flow</li><li>Administrative portal for staff to review and approve claims</li><li>Authorized reseller portal where staff can track and support customers</li><li>Digital storefront where schools can spend earned wallet funds on solutions</li></ul><p id="">This meant that traditionally coded software development was a liability.\u00a0 </p><p id=""><em id="">\u201cIn our work, we always need to make sure we deliver on our promises. We had had agonizing trouble with this in the past with technology builds, since overrun is rampant.\u201d - Paul Thompson, Consenna</em>\u200d</p>`,
    solution: `<p id="">With no time to spare, Consenna opted for a faster development approach to reduce project timelines and costs.\u00a0</p><p id="">The consultancy had already worked with Airdev on previous projects for HP and other clients. It decided to partner with them again for their staff\u2019s background in consulting, experience building for enterprises, and expertise quickly launching complex products.</p><p id="">\u200d<em id="">\u201cHaving partnered with AirDev on previous projects both for HP and other leading technology companies, it was clear that they were best placed to deliver this sort of complex tool.\u201d - Douglas Jeffrey, Chairman at Consenna</em></p><p id="">To make sure that Consenna delivered HP a bespoke digital asset that met all program objectives \u2014 both immediately and over time \u2014 Airdev spent 1 week translating Consenna\u2019s strategy into detailed product specifications, wireframes, and success metrics.\u00a0</p><p id="">After this initial high-touch scoping process, Airdev\u2019s dedicated development team built the app in 3 weeks \u2013 with weekly milestones and check-ins for Consenna to see progress and provide feedback. For the next 5 weeks, Airdev tested the product internally and with HP clients to iterate and add functionality (e.g., reseller self-service) as business needs evolved.\u00a0</p><p id="">Finally, after 2 months, Consenna and the HP team launched the platform at the Bett conference \u2014 a global community event for education technology.\u00a0</p><p id=""><em id="">\u201cAirdev\u2019s ability to synthesize customer requirements distinguishes them from other agencies.\u201d - Neil Hardin, IT Development Project Manager, Consenna</em>\u200d</p>`,
    result: `<p id="">By building with Airdev, Consenna was able to cut its originally scheduled development time by more than half. In its first month live, the custom marketplace facilitated hundreds of school registrations.\u00a0</p><p id="">Today, the online platform supports 30k schools across the UK wanting to upgrade their hardware. Notably, the shift to remote work and schooling that happened due to the pandemic has resulted in a large increase in need for hardware, and this program helped schools make the transition.</p><p id="">As for Consenna, they were able to deliver a successful product that generated very positive feedback and resulted in additional requests from HP for their work.\u00a0</p><p id=""><em id="">\u201cThe relaunch of HP for Education has been a massive success. The platform has enabled us to expand this important program, while making my life easier.\u201d - Michael Pope, Category Manager, HP</em>\u200d</p><p id=""><em id="">\u201cAt a time when Consenna is growing rapidly, it is vital that we consistently deliver for our clients. In this instance, AirDev certainly supported us in ensuring that we not only delivered, but exceeded expectations for HP.\u201d - Paul Thompson, Commercial Director, Consenna</em></p>`,
    galleryImages: [
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/637d56a3b02cf60abd92b073_screely-1669158380832.png",
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/637d569852718b860460cd57_screely-1669158392569.png",
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/637d56d3c00c02bcf733b78e_screely-1669158599052.png",
    ],
    marketplace: true,
    saas: false,
    metaTitle: "Consenna & HP Custom Education Marketplace",
    publishedOn: "Thu Apr 09 2026 01:52:50 GMT+0000 (Coordinated Universal Time)",
    updatedOn: "Thu Apr 09 2026 01:51:24 GMT+0000 (Coordinated Universal Time)",
  },
  {
    name: "Greener Corporation",
    slug: "greener-corporation-no-code-erp",
    archived: false,
    draft: false,
    filteringCategory: "enterprises",
    businessType: "SMB",
    productType: "Enterprise resource planning (ERP) app",
    timeline: "6 months",
    keyResults:
      "A custom-built ERP tailored around Greener Corp\u2019s unique processes, with an estimated lifetime cost of about 75% less than an off-the-shelf system",
    sortOrder: 5,
    companyUrl: "https://greenercorp.com/",
    thumbnailSummary: "How Airdev helped Greener Corp build a custom manufacturing ERP",
    thumbnailImage:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/6431f7a55544d733b3614a00_Manufacturing%20case%20study%20no-code.png",
    heroSummary: `<p><a href="https://greenercorp.com/">Greener Corporation</a> is a global manufacturing company that provides parts and services to major packaged goods companies, packaging machine manufacturers, and flexible packaging converters all over the world. The company had been using an off-the-shelf enterprise resource planning (ERP) system to manage its internal operations. This included handling everything from accounting and purchase orders, to invoices and tracking individual jobs on the factory floor.</p><p>However, as time went on, they found themselves having to adjust their processes to fit the software\u2019s capabilities.\u00a0</p><p><em>\u201cAs our business became more information heavy, with more orders for custom (instead of repeat) parts, we needed a more customized system that we could build around our unique procedures \u2013 from the quote through the production process.\u201d</em> -\u00a0 <em>Director of Analytics and Process Improvement, Aidan Wojtech</em></p><p>But to customize their off-the-shelf ERP, Greener Corp would need to spend a lot of time and money on upgrade efforts. This sparked a search for new solutions. After considering other SaaS options and realizing they would face the same limitations, they considered building their own custom solution. Greener Corp partnered with Airdev to build a totally custom internal ERP system \u2013 in just 6 months.\u00a0</p><p>With the help of Airdev, Greener Corp was able to:</p><ul><li>Develop a custom ERP tailored around their unique processes, with an estimated lifetime cost of about 75% less than an off-the-shelf system\u00a0</li><li>Design a visually simple, intuitive interface that\u2019s easy for employees of all technical abilities to use</li><li>Save employee time with new, streamlined workflows for handling increasing amounts of information\u00a0</li></ul>`,
    quoteImage:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/6431f66c8b0b8b13ceef8b15_Aidan-Wojtech_Greener-Corporation_c_opt.png",
    quote: `"What we do with our off-the-shelf system is not a flip-of-the-switch thing to implement. In the past It has required multiple months and included very expensive consultants. I think we\u2019ve spent the same amount on consultants implementing our off-the-shelf system as we\u2019ve spent building something totally custom with Airdev."`,
    quoteName: "Aidan Wojtech",
    quoteRole: "Director of Analytics and Process Improvement",
    objective: `<p>Greener Corp wanted a system that they could build around their procedures so that every employee would have the information and tools that they need, where they need them. This meant being able to manage everything in their operations, from inventory tracking, job tracking and management, to reporting, price lists management, and parts shipping, all from one internal system.\u00a0</p><p>However, the off-the shelf ERP they had in place was rolling out a new version and Greener Corp realized it was going to require significant effort and money to upgrade in the ways they needed.\u00a0</p><p><em>\u201cThe time commitment involved in implementing an off-the-shelf system actually isn't much smaller than designing a system from the ground up. Those off-the-shelf systems accrued massive technical debt as they tried to build a 'one-size-fits-all' system. When we implemented our current system, we spent months sorting through hundreds of often contradictory settings and feature sets. Working with Airdev, we were able to instead use that time to build our dream workflow from a blank slate \u2013 a much better use of our time and sanity.\u201d - Wojtech\u00a0\u00a0\u00a0</em>\u200d</p>`,
    solution: `<p id="">Wojtech had prior experience building an internal ERP. After doing more research, he realized that Greener Corp had the opportunity to create a new custom ERP at a similar price point.\u00a0</p><p id=""><em id="">\u201cThe key thing was that there weren\u2019t any restrictions on capabilities. The advantage was that it\u2019s significantly faster to build, meaning it\u2019s also significantly less expensive.\u201d</em> Wojtech</p><p id="">Greener Corp auditioned several development firms by having them build apps on top of several smaller internal apps to test the workflow. Greener Corp partnered with Airdev to build their new custom ERP.\u00a0</p><p id=""><em id="">\u201cTop to bottom, Airdev understood what they were doing and were always attentive. So it was ultimately an easy decision.\u201d - </em>Wojtech</p><p id="">Given the size and complexity of the ERP, Greener Corp and Airdev first spent several weeks in intense scoping to align on exact specifications for the build, which included all key features and designs required for the app.\u00a0</p><p id=""><em id="">\u201cThis app was big enough that it had to be a collaborative effort. We weren\u2019t just scoping with one person \u2013 we were scoping with the Airdev team and that made all the difference. The thing that impressed me was the different skill sets within Airdev. We worked with multiple people, and one of the main project managers had an accounting background. That was huge because accounting for inventory in manufacturing is painfully complicated. Airdev having that accounting expertise in-house was a major factor in our project\u2019s success.\u201d</em> - Wojtech</p><p id="">Using the requirements and wireframes created during scoping, Airdev\u2019s development team built the app logic in weekly milestones. Each week, the lead developer would pass their work to a QA specialist for review, then share that work with Greener Corp for testing and review to confirm things were working as they should. </p>`,
    result: `<p id="">Greener Corp's goal was to move off their platform within one year, based on the complex feature set and data migration requirements. The initial build of the new platform was completed in just 6 months, which gave the team half a year to train and onboard their company's users, and to iterate based on real user feedback before the big launch. This allowed the team to reduce risk and ensure that the product exceeds user expectations from day one.</p><p id=""><em id="">\u201cThis is a much more intuitive system to use. Our workforce comprises everyone from high school apprentices to people in their 70\u2019s with a wide range of technical comfort. To have a system like this that\u2019s visually simple and pleasant to use will make an absolute world of difference.\u201d</em> - Wojtech</p><p id="">In addition, Wojtech expressed the larger importance of this custom built ERP, not just for Greener Corp, but for all companies:<br></p><p id=""><em id="">\u201cThis opened my eyes to the fact that custom software is where companies are going. We\u2019re all handling so much more information than we ever used to. We\u2019re going to have to be able to customize our information flow processes and workflows. I think this is the future for all companies \u2013 even in non-tech industries like manufacturing.\u201d</em></p><p>\u200d</p>`,
    marketplace: false,
    saas: false,
    metaTitle: "Greener Corp's Custom ERP Manufacturing Platform",
    publishedOn: "Thu Apr 09 2026 01:52:50 GMT+0000 (Coordinated Universal Time)",
    updatedOn: "Thu Apr 09 2026 01:40:23 GMT+0000 (Coordinated Universal Time)",
  },
  {
    name: "inspo",
    slug: "inspo-airdev-no-code-app",
    archived: false,
    draft: false,
    filteringCategory: "startups",
    businessType: "Startup",
    productType: "Student mentoring platform",
    timeline: "3 months",
    keyResults: "2 rounds of iterations to the platform based on user feedback",
    sortOrder: 17,
    companyUrl: "https://inspo.uk/",
    thumbnailSummary:
      "How Airdev helped inspo build a custom platform connecting students from all backgrounds to professional mentors",
    thumbnailImage:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/63c088ec34adb07dcea369a4_desola-lanre-ologun-IgUR1iX0mqM-unsplash%20(1)%20(1).jpg",
    heroSummary: `<p id="">After founding and launching The Pay Index, which provides transparency tools to students and business professionals about salary pay and careers, inspo CEO James Rust turned his attention to the issue of social mobility in the UK.\u00a0</p><p id=""><em id="">\u201cSocial mobility in the UK is not great. If you\u2019re born poor, the chances of you remaining poor are high in the UK. So for example, if a student wants to find a career in banking, but none of their family/friends have ever worked in banking, they have limited resources to utilize. We wanted to build a tool that would provide opportunities to students that they wouldn\u2019t otherwise come across.\u201d - James Rust, Founder &amp; CEO of The Pay Index and inspo</em></p><p id="">To prove the concept for the tool in the UK first, Rust and his team wanted to launch a pilot app quickly that would be easy to iterate on. Rust partnered with Airdev to develop inspo, a custom student mentoring platform to connect undergraduates from all backgrounds with working professionals, with a focus on social mobility.</p><p id="">With the help of Airdev, Rust was able to:</p><ul id=""><li id="">Develop a platform that matches student mentees with professional mentors from different businesses and industries</li><li id="">Complete 2 rounds of iterations to the platform based on user feedback</li><li id="">Sign up 10 paid users (i.e. companies) on the platform in less than a year</li></ul>`,
    quoteImage:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/63c085f421484129fce5efec_James-Rust-The-Pay-Index_.jpeg",
    quote:
      "What is really interesting is the quality of the web app that we were able to build with Airdev. It had the functionality that we wanted for a pilot. And we've had two subsequent rounds of development work done with Airdev on the site driven by user feedback. One that's been done already. And then we've just started a third iteration to gamify it.",
    quoteName: "James Rust",
    quoteRole: "inspo founder & CEO",
    objective: `<p id="">The inspo team\u2019s goal was to open the door to resources and connect students in the UK to professionals that they would normally not have access to. This included providing highly filtered search criteria for mentees to search out desired mentors by things like race, ethnicity, sexual orientation, gender, abilities, industry, etc. In addition, the user interface and experience (i.e. user onboarding, messaging, etc.) needed to be simple to navigate and build user trust.</p><p>As the CEO of The Pay Index, Rust didn\u2019t have the time to spend building the full platform with the desired level of functionality and design as quickly as he wanted.\u00a0</p><p>\u200d<em id="">\u201cI was looking at different development options, but I quickly realized I didn\u2019t have the time fundamentally to build it out myself.\u201d - Rust</em>\u200d</p>`,
    solution: `<p id="">Proving the concept first and gathering user feedback for future improvements was very important to Rust \u2013 after all, the general goal of inspo was to help those who need it the most. To quickly develop a pilot platform, the inspo team partnered with Airdev to build the first version of the app\u00a0</p><p id="">\u200d<em id="">\u201cWhat was really nice was that the team at Airdev really saw the value of what we\u2019re trying to do. This is not about trying to make us all millionaires, it\u2019s about helping others. While we\u2019re not a charity, we are a business for good \u2013 and we have shareholders to answer to. And Airdev understood all this.\u201d - Rust</em></p><p id="">Airdev\u2019s dedicated product manager used their experience building marketplace MVPs to guide Rust and his team through each major decision-point in the platform\u2019s flow. The idea was to build the pilot lean in order to test the product as quickly as possible so that inspo could gather user feedback and make the next version better.</p><p id="">\u200d<em id="">\u201cThe people at AIrdev encouraged us to focus on the MVP, make sure that works, and then make sure we\u2019re getting feedback. Then after feedback, they recommended gradually upgrading the product to make it more valuable to users. We may think we know what users want, but we really need to hear from them what\u2019s working and what\u2019s not. So I might have these brilliant ideas early on, but they might be totally irrelevant in terms of improving the product experience.\u201d - Rust</em></p><p id="">To get inspo to market as quickly as possible, Airdev built and tested the complete application in weekly milestones. During each deliverable milestone, inspo was provided testing instructions so that they could confirm everything was working as expected.\u00a0</p><p id="">\u200d<em id="">\u201cI was pleasantly surprised with the speed of turnarounds. And bearing in mind that they were dealing with non-experts in terms of how to run a tech practice. They were very patient with me as well, which creates that bond of trust. For instance, if there was something we thought we might have signed off on, or something we found wasn\u2019t quite right a few weeks later that needed changing, Airdev was generous with their time and that pays back.\u201d - Rust</em>\u200d</p>`,
    result: `<p id="">inspo was able to build its initial MVP in just 2 weeks \u2013 with a total product timeline of 3 months. In less than a year, they\u2019ve signed up 10 paying company customers,\u00a0 been able to get students and mentors matched for active mentoring, and they\u2019re getting testimonials and feedback on the platform for further development iterations.\u00a0</p><p id=""><em id="">\u201cI\u2019m proud of what we\u2019ve built\u2026when we show the app to clients they think it\u2019s really cool. It\u2019s a really clean interface. Airdev\u2019s team has built something that is pretty special.\u201d - Rust</em>\u200d</p><p id=""><em id="">See inspo\u2019s app in</em><a href="https://play.google.com/store/apps/details?id=com.inspomentoring.inspomentoring&gl=GB&pli=1" target="_blank"><em id=""> Google Play Store</em></a><em id=""> and </em><a href="https://apps.apple.com/gb/app/inspo-mentoring/id1633202122" target="_blank"><em id="">Apple App Store</em></a><em id="">.</em>\u200d</p>`,
    galleryImages: [
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/63c088691b3b4c789d341552_screely-1673562175760.png",
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/649fc262e7e4dcda62a72824_14.png",
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/649fc26519ddf795aac0e618_15.png",
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/649fc2683a0a0152e88a0801_16.png",
    ],
    marketplace: false,
    saas: false,
    metaTitle: "inspo Platform Connecting Students & Mentors",
    publishedOn: "Thu Apr 09 2026 01:52:50 GMT+0000 (Coordinated Universal Time)",
    updatedOn: "Thu Apr 09 2026 01:41:24 GMT+0000 (Coordinated Universal Time)",
  },
  {
    name: "Kidsbook",
    slug: "kidsbook-marketplace-app",
    archived: false,
    draft: false,
    filteringCategory: "startups",
    businessType: "Startup",
    productType: "2-sided marketplace",
    timeline: "6 weeks",
    keyResults: "1000+ providers signed up",
    sortOrder: 14,
    companyUrl: "https://kidsbook.io/",
    thumbnailSummary:
      "How Airdev helped Kidsbook build a custom marketplace in just 6 weeks to connect parents with kids activity providers",
    thumbnailImage:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/635075037ab429484ab21afb_kidsbook%20(2).png",
    videoLink: "https://www.youtube.com/watch?v=DBewniAxMTU",
    heroSummary: `<p id=""><em id="">\u200d</em>Kidsbook started with the idea to launch a kids activity marketplace to connect parents and providers in one digital location. To get the concept off the ground fast, they opted to leverage the technical expertise of an agency to avoid climbing the learning curve themselves.</p><p id="">Kidsbook partnered with Airdev to build a custom 2-sided marketplace app that allows verified providers to offer kids activities that parents can register their kids for.\u00a0</p><p id="">With the help of Airdev, Kidsbook was able to:</p><ul id=""><li id="">Launch a custom-built marketplace in 6 weeks</li><li id="">Sign up 1000+ providers on the platform</li><li id="">Expand the platform and hire new staff during and beyond the COVID-19 pandemic</li></ul>`,
    quoteImage:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/6337409016dc1087f0f5711c_Untitled%20design%20(13).png",
    quote: `"If we went on our own, we would have gotten stuck on some of these hurdles that would have taken us quite a while to get past. But to be able to access that braintrust inside Airdev definitely sped things up for us\u2026we even discovered more capabilities than we initially expected."`,
    quoteName: "David Vitek",
    quoteRole: "CEO and Founder of Kidsbook",
    objective: `<p id="">Kidsbook\u2019s goal was to be a hub for booking quality, verified kids activities from providers that parents could trust. To do this, they needed to build a platform that allowed activity providers to register, get vetted, and log their events, and parents to browse and sign their kids up for activities. This included scheduling and payments for bookings.\u00a0</p><p id="">The founder and CEO David Vitek knew that building a marketplace platform through traditional programming would be cumbersome and slow (he had already co-founded <a id="" href="https://hipages.com.au/">hipages</a>, the most visited site in the Australian home improvement and building sector, with web traffic in excess of 1M visitors per month). Instead, he wanted a leaner development process that could get the concept off the ground fast. He decided to find a development partner that could get the concept off the ground fast.\u00a0</p><p id="">However, Kidsbook didn\u2019t have the in-house expertise and knowledge to build as quickly and cost-effectively as they wanted.\u00a0</p>`,
    solution: `<p id="">To take advantage of a faster and more cost-effective development process and also offer a convenient and trustworthy experience for parents, Kidsbook partnered with Airdev to build the platform. As an experienced development agency, Airdev provided Kidsbook with the expertise, experience, and reliability they needed to confidently launch their marketplace.\u00a0</p><p id="">During the scoping process, Airdev\u2019s dedicated product manager used their experience building digital marketplaces to walk David through each major feature decision-point in the product flow. This included recommendations for what to include now vs. push for later in order to achieve the leanest version of the product. All of this then led to the creation of a product roadmap that translated Kidsbook\u2019s vision into a detailed format that developers could use to hit agreed upon deadlines.\u00a0\u00a0</p><p id=""><em id="">\u201cIt wasn\u2019t just the build of the product. It was also the product ideas, thinking, and discussions around where we wanted the product to go. And especially in those early phases \u2013 while we\u2019re doing some really fast learning \u2013 Airdev was really able to keep up with the pace.\u201d - David Vitek</em></p>`,
    result: `<p id="">Kidsbook was able to get their new marketplace product to market on budget in just 6 weeks. Because of this, they were able to keep promises and start getting activity providers signed up on the platform. They retained an Airdev team on a recurring basis for ongoing product iterations as feedback came in from clients using the platform. </p><p id="">Thanks to their ability to launch fast and rapidly react to market demands, Kidsbook was able to expand its team and platform, scaling to have 2 internal developers and signing up 1000+ providers on the platform.</p><p id=""><em id="">\u201cAfter working with Airdev, we were able to make this product come to life...We launched Kidsbook within 6 weeks, then we were able to do continuous iterations based on feedback we were getting from the market.\u201d </em>- <em id="">David Vitek</em></p>`,
    galleryImages: [
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/637d59fdc1ec2d5ca9f0fc89_screely-1669159359596.png",
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/637d5a05c00c0211c036af90_screely-1669159374832.png",
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/637d5a0807e7e51a46eee776_screely-1669159387926.png",
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/637d5a0b3c9615557661c624_screely-1669159401799.png",
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/637d5a12078799e545c05574_screely-1669159414331.png",
    ],
    marketplace: true,
    saas: false,
    metaTitle: "Kidsbook Marketplace Connecting Parents & Partners",
    publishedOn: "Thu Apr 09 2026 01:52:50 GMT+0000 (Coordinated Universal Time)",
    updatedOn: "Thu Apr 09 2026 01:46:40 GMT+0000 (Coordinated Universal Time)",
  },
  {
    name: "Lawclick",
    slug: "lawclick-marketplace-startup",
    archived: false,
    draft: true,
    filteringCategory: "startups",
    sortOrder: 1,
    thumbnailSummary:
      "See how Lawclick quickly built a marketplace to connect lawyers and users of legal services.",
    thumbnailImage:
      "https://uploads-ssl.webflow.com/62aa5d914f45160a7f155660/62b9d1de487add460f376b0e_cs-thumb-circooles.png",
    videoLink: "https://www.youtube.com/watch?v=vICj9RpdYGI&t=4s",
    marketplace: false,
    saas: false,
    updatedOn: "Wed Oct 19 2022 22:09:26 GMT+0000 (Coordinated Universal Time)",
  },
  {
    name: "MY NFT Alerts",
    slug: "my-nft-alerts-web-platform-no-code",
    archived: false,
    draft: false,
    filteringCategory: "startups",
    businessType: "Startup",
    productType: "Portfolio tracking app",
    timeline: "6 weeks",
    keyResults: "Rapid user adoption",
    sortOrder: 15,
    companyUrl: "https://www.mynftalerts.com/",
    thumbnailSummary:
      "How Airdev helped My NFT Alerts build a custom platform for NFT holders to track, trade and set personalized floor price alerts",
    thumbnailImage:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/635079364569b5471f0fc12d_nft.jpeg",
    heroSummary: `<p id=""><em id="">My NFT Alerts helps current and potential NFT investors track entire NFT portfolios and news on one single dashboard.</em>\u200d</p><p id="">After purchasing his first NFT, Pablo Lerdo found himself struggling to stay on top of the prices of his NFTs. Everyday he had to painstakingly visit each NFT\u2019s collection on websites like OpenSea to keep track of his purchases.\u00a0</p><p id=""><em id="">\u201cThe only way to stay on top of portfolios in the NFT space was to individually go look at each of the different collections that you own. As I started to talk to other folks, I saw I wasn\u2019t the only one who was tracking all the different prices across multiple spreadsheets and different websites. One day, I was looking at my Apple iPhone stocks app to track my traditional investments and that\u2019s when it clicked. I knew I needed a simple app to track everything in the NFT space, like portfolios, market news, and trends.\u201d - Pablo Lerdo, Founder of My NFT Alerts.\u00a0\u00a0</em>\u200d</p><p id="">To prove market fit and get product traction fast, Lerdo knew he wanted to build the app quickly. He had already built an initial MVP for his other startup and knew the value of rapid development, but didn\u2019t have the time to develop the app himself. Lerdo partnered with Airdev to build a custom one-stop-shop platform for NFT holders to track, trade and set personalized floor price alerts for their NFTs.</p><p id="">With the help of Airdev, My NFT Alerts was able to:</p><ul id=""><li id="">Sign up 130+ users, including 30+ paid users, on the platform in 4 months</li><li id="">Seamlessly integrate multiple APIs syncing real-time data from various NFT sources\u00a0</li><li id="">Receive overwhelmingly positive feedback</li></ul>`,
    quoteImage:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/633f157b4522746694c79a86_1663883861414.jpeg",
    quote:
      "\u201cI thought that the scoping process was the bread and butter of the whole thing. Once that was done and the actual development started, they knew perfectly what they were doing and what they were building because we had established everything during scoping.\u201d",
    quoteName: "Pablo Lerdo",
    quoteRole: "My NFT Alerts Founder",
    objective: `<p id="">Lerdo\u2019s goal was to help NFT holders (and the \u201cNFT curious\u201d) better understand activity around their NFT investments in one central location. This included providing real-time information around the investments other people are making, price activity around individual NFTs and collections, and how to know when to get into a new NFT project.\u00a0</p><p id="">To fetch the newest NFT information for users, Lerdo\u2019s app needed to link to several outside information sources through APIs. In addition, it would need to offer different features for users to track, trade, create watchlists, and set personalized floor prices and gas alerts available via SMS and email.</p><p id="">However, as the founder of another startup (<a href="https://www.datalogz.io/" target="_blank">Datalogz.io</a>), Lerdo didn\u2019t have the time to spend learning the complicated new functionality needed to build the app as quickly as he wanted.\u00a0</p><p id=""><em id="">\u201cI knew that if I wanted something out quickly to prove product market fit and get some traction with initial customers, I needed a fast development approach. But I was very busy with my other startup and I was working full-time, too, so I needed experienced developer services.\u201d\u00a0- Pablo Lerdo</em>\u200d</p>`,
    solution: `<p id="">A professional web app look and design was a big deal to Lerdo \u2013 afterall, the goal of his idea was to help people feel more confident and empowered in making NFT investments. To get there, he partnered with Airdev to guarantee that his app would not only be built quickly, but also have a beautiful and simple user experience.\u00a0\u00a0</p><p id="">\u200d<em id="">\u201cI felt that Airdev was the highest quality among the other top agencies and developers. So I just knew if I was going to put my development in somebody else\u2019s hands, it was just going to be Airdev.\u201d - Pablo Lerdo</em></p><p id="">Before jumping into development, Airdev\u2019s dedicated project manager spent 1 month aligning Lerdo\u2019s vision to specific features to build into the product roadmap. This included recommendations for how to launch the leanest version of the platform quickly, while still meeting all the needs that would make this app unique and valuable to its users.\u00a0\u00a0</p><p id=""><em id="">\u201cI knew that if I ever was going to hire a developer to help me build something quickly that it was going to be Airdev directly.\u201d\u00a0</em><em id="">- Pablo Lerdo</em>\u200d</p><p id="">To retrieve information from outside NFT data sources like OpenSea, Etherscan, and NFTPort, Lerdo\u2019s app needed to integrate multiple APIs. Airdev\u2019s team of developers used its proprietary API connector tool to integrate the APIs quickly so that Lerdo\u2019s app could function smoothly.</p><p id=""><em id="">\u201cWhenever we hit roadblocks around information that we could extract depending on the different endpoints on APIs, my Airdev developer would go out and find new companies that would give us the information that could solve the problem. They really did go above and beyond here.\u201d\u00a0- Pablo Lerdo</em>\u200d</p>`,
    result: `<p id="">Lerdo was able to bring his web app to market in just 6 weeks. In a 4-month span, he had over 150 users sign up, with over 30 converted paid users, and hit $510 in monthly recurring revenue. In addition, he has received continuous positive feedback from users through Twitter, emails, in person, and in the app.</p><p id=""><em id="">\u201cI've had so many people reach out and thank me. They've been wanting this for some time and are so happy that this app just alleviated a lot of their pain.\u201d - Pablo Lerdo</em>\u200d</p><p id="">Not one to sit around, Lerdo is actively fielding new and outstanding user requests around how to make his app even better. He plans to continue iterating his product with new features over time, leaning on Airdev to accomplish the more complex additions.\u00a0</p>`,
    galleryImages: [
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/637d5bf22fc3524dc54420f0_screely-1669159885673.png",
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/637d5bf46e9343554165415a_screely-1669159901687.png",
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/637d5bf6efda9d57c5f62a90_screely-1669159911431.png",
    ],
    marketplace: false,
    saas: false,
    metaTitle: "My NFT Alerts Custom Fintech Platform for Traders",
    publishedOn: "Thu Apr 09 2026 01:52:50 GMT+0000 (Coordinated Universal Time)",
    updatedOn: "Thu Apr 09 2026 01:52:08 GMT+0000 (Coordinated Universal Time)",
  },
  {
    name: "Resolis",
    slug: "resolis",
    archived: false,
    draft: false,
    filteringCategory: "enterprises",
    businessType: "Enterprise",
    productType: "Internal tool",
    timeline: "5 months",
    keyResults:
      "Standardization of niche, manual processes for teams operating across the UK",
    sortOrder: 6,
    companyUrl: "https://resolis.com/",
    thumbnailSummary:
      "How Airdev helped Resolis build an internal tool to streamline their public infrastructure asset management services",
    thumbnailImage:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/6698333e120200f6df1df8ad_Resolis%20no-code%20internal%20tool.jpg",
    heroSummary: `<p id="">Resolis is a large company that manages public infrastructure assets, such as hospitals and schools, in the UK. With several different teams operating across the UK, they decided to build a custom internal app to standardize and streamline their manual processes, reporting, and job training.</p><p id=""><em id="">"Because we operate in a very niche industry, we needed something custom. We wanted to take all of our offline, manual processes and build them into software so that we're doing things as efficiently as possible. We also needed to get something up and running fast." \u2013 Stelios Kornaros, Finance Director at Resolis</em>\u200d</p><p id="">To speed up the development process, Resolis sought out companies who could build what they needed quickly. After interviewing multiple firms, they decided to partner with Airdev to develop their internal tool.</p><p id="">With the help of Airdev, Resolis was able to:</p><ul id=""><li id="">Develop an internal tool and client portal with customized views for a wide variety of user roles and permissions \u2013 implemented within 5 months</li><li id="">Expand the software's functionality on an ongoing basis</li><li id="">Standardize niche, manual processes for all teams operating across the UK</li></ul>`,
    quoteImage:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/669834605af3c466c4e85594_Stelios%20Kornaros_Resolis.webp",
    quote: `"For me it was important to find a team that I could really communicate with and that would understand what we were trying to do. Airdev ticked all the boxes from a communication and professionalism standpoint. They also had a very strong reputation in the development space."`,
    quoteName: "Stelios Kornaros",
    quoteRole: "Finance Director at Resolis",
    objective: `<p id="">Resolis' goal was to improve their service delivery by developing a custom app that standardized all of their internal processes for current and new staff. But they needed a development solution that was faster than traditional programming.</p><p id=""><em id="">"When I got tasked to lead the development of a tool, I chose not to develop from scratch with a traditional approach. I instead wanted to build our app with a more streamlined, secure, and future-proof development process." - Kornaros</em>\u200d</p>`,
    solution: `<p id="">To find a company that could quickly develop their complex internal tool, Resolis interviewed several different companies that could quickly develop custom software.</p><p id=""><em id="">"What stood out to me about Airdev was the fact that they clearly took the project seriously. They had a very professional approach to development. I'm the Finance Director at Resolis, so managing the development of software is not my full-time job. For me it was important to find a team that I could really communicate with and that would understand what we were trying to do. Airdev ticked all the boxes from a communication and professionalism standpoint. They also had a very strong reputation in the development space." - Kornaros</em></p><p id="">Once Resolis officially partnered with Airdev, they dove headfirst into a month-long scoping phase where together they outlined all app features, logic, and timelines. <br><br><em id="">"Every bit of development started with a meeting, almost like an interview process, for them to understand what we were trying to accomplish. They helped us brainstorm solutions to problems we had, including how to create something that allowed our various user roles to have different customized views and permissions." - Kornaros</em></p><p id="">By going through such a detailed scoping process early on, Airdev's development team was able to quickly and accurately build and QA Resolis' internal software in just 3 months. From there, Resolis spent 1 month thoroughly testing every aspect of the tool and flagging any issues using Airdev's custom widget for marking and creating tickets for their team to resolve.</p>`,
    result: `<p id="">In just 5 months, Resolis\u2019 entire UK team adopted the new custom software, which streamlined and standardized previously manual tasks. The tool also functions as a client portal, providing user-specific access during key stages of the service delivery process. Resolis continues to expand the software\u2019s functionality with Airdev, ensuring all of their internal processes are cloud-based.</p><p id=""><em id="">\u201cWe see this process of adding functionality continuing with Airdev. They\u2019re a very technically competent extension of our team. They\u2019re always trying to develop our software in the most effective long-term way possible, and in the time that we need it.\u201d - Kornaros\u00a0</em>\u200d</p>`,
    marketplace: false,
    saas: false,
    metaTitle: "Resolis Custom Enterprise Tools for Asset Management",
    publishedOn: "Thu Apr 09 2026 01:52:50 GMT+0000 (Coordinated Universal Time)",
    updatedOn: "Thu Apr 09 2026 01:31:38 GMT+0000 (Coordinated Universal Time)",
  },
  {
    name: "Teach for America",
    slug: "teach-for-america-no-code-crm",
    archived: false,
    draft: false,
    filteringCategory: "enterprises",
    businessType: "National nonprofit",
    productType: "Internal hub",
    timeline: "4 weeks",
    keyResults: "Ability to manage the organization at scale",
    sortOrder: 3,
    companyUrl: "https://www.tfabay.org/",
    thumbnailSummary:
      "How Airdev helped Teach for America build a custom internal hub to support corps members across their journey",
    thumbnailImage:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/635075d6712da824635efa1d_tfa%20(1).jpeg",
    heroSummary: `<p id=""><em id="">Teach for America is a non-profit organization working to close the educational achievement gap by enlisting recent college graduates to teach in low-income communities.\u00a0</em>\u200d</p><p id="">Its Bay Area regional office sought to replace a hodgepodge of spreadsheets, email blasts, and shared folders with a new workflow system that would make it easier for staff to support active teachers. They wanted a custom web application, but believed this was out of reach due to the cost and time of traditional software development.</p><p id="">However, that changed when they discovered that a custom-built app could give them what they wanted for a fraction of the cost of traditional development. Teach for America partnered with Airdev to build a custom internal hub that has expanded over the years to do so much more.\u00a0\u00a0</p><p id="">With the help of Airdev, Teach for America was able to:<strong id="">\u200d</strong></p><ul id=""><li id="">Develop a custom CRM-like tool in just 4 weeks for staff to seamlessly support active teachers in the Bay Area</li><li id="">Expand the app with the addition of new onboarding, training, and placement portals to support corps members across <em id="">every</em> stage of their journey (e.g. onboarding, training, and placement)\u00a0</li><li id="">Integrate the app with Salesforce </li></ul>`,
    quoteImage:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/62db446fd3ab22feae2f3820_Teach%20for%20America_Eric%20Scroggins%20headshot.jpeg",
    quote:
      "\u201cAirdev has helped our Bay Area region to ditch the spreadsheets in order to better support our teachers. In just one month, we built an internal CRM system to fit our unique data needs and allow coaches to add and review notes on the go, right from their phones.\u201d",
    quoteName: "Eric Scroggins",
    quoteRole: "Chief Strategy & Program Officer at Teach for America",
    objective: `<p id="">Struggling with version control, lack of personalization, and document management across its network of platforms, Teach for America sought to create a custom internal workflow tool that could do the following:\u00a0\u00a0</p><ul id=""><li id="">Create personalized experiences for a wide range of user roles,<strong id=""> </strong>including corps members, coaches, administrative staff, external school partners, etc.</li><li id="">Track and report data on multiple KPIs to uncover actionable insights</li><li id="">Enable tight role-based security and permissions</li><li id="">Integrate with Salesforce\u00a0</li><li id="">Automate emails to to send personalized notifications to individuals and groups\u00a0</li><li id="">Integrate with Box to<strong id=""> </strong>store large quantities of data files</li></ul><p id="">However, all of its internal tech resources were busy and hiring a contract software developer to build this would be too expensive. Teach for America believed creating a network of Google Sheets was its only option for managing workflows on its budget.\u00a0</p>`,
    solution: `<p id="">A former employee suggested a faster and more flexible development alternative. Teach for America could design exactly what it wanted (interface + business logic) and achieve it in a fraction of the time and cost of hiring a contract developer.\u00a0</p><p id="">Teach for America needed help building a tool that would meet their robust list of specific requirements.</p><p id="">That\u2019s where Airdev stepped in.</p><p id="">Airdev translated Teach for America\u2019s vision and robust list of tool requirements into detailed functional product specifications, wireframes, and success metrics. With this, the development team used its rapid and iterative process to build a fully functional product in just 4 weeks and on budget.\u00a0</p><p id="">Named the \u201cTeacher Hub\u201d, this first iteration of the tool allowed staff to monitor teachers\u2019 progress along a range of KPIs to determine where their efforts would be best spent providing support.\u00a0</p><p id="">The web app was built and deployed with the following structure:</p><ul id=""><li id="">3 user roles: admins, staff, and corps member can all have personalized experiences</li><li id="">Self-service: teachers can login to track their metrics and submit self-assessments</li><li id="">Workflow management: coaches can login to view their portfolio at a glance\u00a0 and update metrics and notes</li><li id="">Data visualization: complex dashboards showing heat maps and data visualizations broken down by sub-region, dual-level coaching structure</li></ul><p id="">After the launch, Airdev established a consistent team to implement further app iterations. This included prioritizing features from Teach for America\u2019s roadmap and collaborating to improve the functionality and user experience over time.\u00a0</p>`,
    result: `<p id="">Based on the success of the original app, Teach for America and Airdev have continued a close partnership. This has allowed the internal hub to expand and evolve to meet changing demands and solve efficiency challenges \u2013 including helping staff better support teachers at every stage of their journey.\u00a0</p><p id="">Since then, the following new portals have been added to the Teacher Hub:</p><ul id=""><li id="">Onboarding: task management tool with personalized checklists for each incoming teacher (certifications, documents, hiring, etc.)</li><li id="">Training: CRM tool for coaching/support of teachers during a 6-week training program</li><li id="">Placement: internal job board and interview planning tool for school partners looking to hire corps members</li></ul><p id="">Today, Teach for America\u2019s app consists of dozens of pages and hundreds of workflows, including thousands of users, nearly 50,000 tasks assigned, and tens of thousands of updated metrics. With this, they can continue to help incoming corps members through every stage of their journey, from their onboarding and all the way through their training and placement.</p><p id="">Each component of the Hub enables Teach For America\u2019s staff members to collect data from corps members and external partners seamlessly, and use it to make decisions about how to best allocate resources. This leads to better teacher preparation and support, which helps facilitate better student outcomes.</p>`,
    marketplace: false,
    saas: false,
    metaTitle: "Custom Tools for Nonprofit Teach for America",
    publishedOn: "Thu Apr 09 2026 01:52:50 GMT+0000 (Coordinated Universal Time)",
    updatedOn: "Thu Apr 09 2026 01:49:07 GMT+0000 (Coordinated Universal Time)",
  },
  {
    name: "TheHair.App",
    slug: "thehair-app",
    archived: false,
    draft: false,
    filteringCategory: "startups",
    businessType: "Startup",
    productType: "AI App",
    keyResults:
      "141% increase in salon-facing treatments and a 70% boost in hair care sales among salons using the app",
    sortOrder: 9,
    companyUrl: "https://thehair.app/",
    thumbnailSummary:
      "How TheHair.App used Airdev's freelance talent to maintain and integrate AI features on a budget",
    thumbnailImage:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/6629510c964641f9de1e196d_The%20Hair%20App-No-Code-AI-Airdev%20(1).jpg",
    customerLogo:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/662951307d793525c985a2d2_hair%20app%20logo.jpg",
    heroSummary: `<p id="">TheHair.App founder Richard Kavanagh needed a way to integrate critical new AI features in his existing product at a time when he also needed to scale back costs.</p><p id=""><em id="">"Instead of chasing investment, I decided to focus on creating a great product that the market would love, and grow revenue organically from subscriptions. But doing this meant big cost cutbacks, including team downsizing." - Kavanagh</em>\u200d</p><p id="">Kavanagh sought a singular developer who could be available for the hours he had a budget for. He discovered Airdev's Flex model and matched with a top freelance developer to efficiently support and extend TheHair.App's capabilities.</p><p id="">With Airdev's Flex model, he had:</p><ul id=""><li id="">Access to a top 1% full stack developer on an as-needed basis \u2013 without the burden of high overhead from full-time staff</li><li id="">Ongoing app maintenance and product roadmap advancement</li><li id="">A 141% increase in salon-facing treatments and a 70% boost in hair care sales among salons using the app</li></ul>`,
    quoteImage:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/662952bc642719a6d8f83c51_Richard%20Kavanagh-Hair%20App.jpeg",
    quote: `"I found Airdev and they\u2019ve been an absolute godsend for me as the founder and CEO, and for the company as a whole. It\u2019s been an incredible opportunity to easily hire highly skilled experts for the specific work and hours we need, without the stress of hiring full-time staff. If things ever get tough financially, I can pause or end the contract without any long-term commitments, then pick it back up again when ready. Overall, it's been a huge relief to have this flexibility and support."`,
    quoteName: "Richard Kavanagh",
    quoteRole: "Founder of TheHair.App",
    objective: `<p id="">TheHair.App's goal was to simplify the hair consultation and treatment process for salons and stylists by scanning and assessing clients' hair types and face shape (using photos) to provide perfect-match hair treatments and recommendations.</p><p id="">To do this, they needed to integrate complex generative AI features on top of their existing app. However, they lacked the investment money to fund an entire team of full-time developers who could continue development and properly launch the app.</p><p id=""><em id="">"I needed to find somebody who could not only be available for maintenance for a certain number of hours each month, but also have the requisite skillset to make progress integrating new features to the product roadmap." - Kavanagh</em>\u200d</p>`,
    solution: `<p id="">After finding Airdev's Flex model offering, which provides access to the top 1% development talent on a fractional basis, Kavanagh decided to hire one of Airdev's freelance developers to extend and maintain TheHair.App.</p><p id=""><em id="">"I found Airdev and they've been an absolute godsend for me as the founder and CEO, and for the company as a whole. It's been an incredible opportunity to easily hire highly skilled experts for the specific work and hours we need, without the stress of hiring full-time staff. If things ever get tough financially, I can pause or end the contract without any long-term commitments, then pick it back up again when ready. Overall, it's been a huge relief to have this flexibility and support." - Kavanagh</em>\u200d</p><p id="">To get matched with the right developer, Kavanagh shared his needs with Airdev's Customer Success Manager, who then presented several best-fit freelance developers for TheHair.App to choose from.</p><p id=""><em id="">"I really loved the personalized onboarding process with Airdev. Unlike other platforms where I have to sift through countless profiles and portfolios, Airdev took the time to understand my business and match me with the right developers. This streamlined the decision-making process and saved me from the hassle of finding the right fit on my own." - Kavanagh</em></p><p id="">Once matched, Kavanagh and his developer regularly collaborated through calls and messaging platforms to plan monthly goals and deadlines, tracked conveniently in Airdev's Flex client portal. In the portal, Kavanagh also had the ability to easily manage and adjust hours as needed for the upcoming month.</p>`,
    result: `<p id="">With the help of an Airdev developer, TheHair.App now offers advanced generative AI features for hairstylists to provide more personalized, thorough customer consultations. They're also continuing work together to add new elements to the product roadmap, including integrating APIs with salon software, booking platforms, and e-commerce stores to modernize hairstylists' businesses and boost sales in an industry traditionally offline.</p><p id=""><em id="">\u201cWorking with Airdev, I've found a developer who's not only highly technically skilled, but also brings fresh suggestions and solutions for improving TheHair.App\u2019s existing data management, payments, machine learning elements, and custom coding. Having the ability to tap into somebody to keep the lights on and nicely grow and iterate the product is amazing.\u201d - Kavanagh\u00a0</em></p><p id="">So far, TheHair.App has led to a 141% increase in salon-facing treatments and a 70% boost in hair care sales among salons using the app.</p>`,
    marketplace: false,
    saas: false,
    metaTitle: "AI on a Budget for TheHair.App",
    publishedOn: "Thu Apr 09 2026 01:52:50 GMT+0000 (Coordinated Universal Time)",
    updatedOn: "Thu Apr 09 2026 01:34:36 GMT+0000 (Coordinated Universal Time)",
  },
  {
    name: "Tributi",
    slug: "tributi-latin-american-turbo-tax-no-code",
    archived: false,
    draft: false,
    filteringCategory: "startups",
    businessType: "SMB",
    productType: "Tax management software",
    timeline: "5 weeks",
    keyResults:
      "Supported 20k daily users and launched a successful YCombinator bid",
    sortOrder: 11,
    companyUrl: "https://www.tributi.com/",
    thumbnailSummary:
      "How Airdev helped Tributi build a tax management software for Latin America in just 5 weeks",
    thumbnailImage:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/63507625712da8bcd35f011e_tributi.jpeg",
    heroSummary: `<p id="">Tributi founders Andr\u00e9s V\u00e9lez and Sim\u00f3n Gonz\u00e1lez were fed up with the painful, confusing, and costly process of filing taxes in their home country of Colombia.</p><p id=""><em id="">\u201cIt is common for the preparation of the income statement to be more expensive than the payment of the tax itself, which is not an efficient tax structure.\u201d - Andr\u00e9s V\u00e9lez, Founder and CEO of Tributi.\u00a0</em>\u200d</p><p id="">The founders wanted to build a tax management software like TaxAct and Intuit (which owns<a id="" href="https://turbotax.intuit.com/"> TurboTax</a>) to automate and simplify the tax filing process for all South and Latin Americans. V\u00e9lez and Gonz\u00e1lez had a clear vision for the product and user experience they wanted to build, but they simply didn\u2019t have the background in programming to do it.</p><p id="">To get around the programming barrier, Tributi partnered with Airdev to quickly build and launch a fully functional product.<br></p><p id="">As a result:</p><ul id=""><li id="">Tributi raised $800k in early investment from players like Y Combinator, Foundation Capital, and Graph Ventures </li><li id="">Latin American taxpayers and accountants can now prepare tax returns within 30 minutes, saving them an average of COP$100-$300K (US$100-175) on their tax returns</li></ul>`,
    quoteImage:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/62aa5d924f451696a7155830_tributi.jpeg",
    quote:
      "\u201cAirdev has been critical to our venture's progress. They truly offer a seemingly impossible value proposition: they not only sit in the intersection between quality, speed, and cost, but also bring business wits into the process. In the end, I truly considered Airdev our partners in our venture.\u201d",
    quoteName: "Andr\u00e9s V\u00e9lez",
    quoteRole: "Founder and CEO of Tributi",
    objective: `<p id="">Tired of agonizing over filing taxes, Tributi\u2019s founders spotted an opportunity to build a tax filing app for Colombian taxpayers.</p><p id="">They saw how automating the process could facilitate better tax filing preparations for an entire society and make it easier for South and Latin American governments to generate revenue \u2013 qualifying it as a socially viable product. So they set out to build a software product that would accomplish this, along with a simple user interface that would generally improve the stressful experience and make taxpayers feel in control of the process at all times.</p>`,
    solution: `<p id="">With experience in the finance industry and as taxpayers themselves, V\u00e9lez and Gonz\u00e1lez had a clear vision of the tax engine and user experience they wanted to build, but simply didn\u2019t have the background in programming to build it the way they dreamed, on the timeline they needed it.\u00a0</p><p id="">When time started running out, V\u00e9lez looked for ways to get around the programming barrier. He started working with Airdev as a speedier development option.</p><p id=""><em id="">\u201cWorking with Airdev put the power of building the product back in my hands and we were able to build very quickly, that we could iterate on ourselves. So that basically changed the dynamic for us.\u201d - Andr\u00e9s V\u00e9lez</em></p><p id="">To ensure everyone was on the same page about what to build, Airdev\u2019s dedicated Product Manager worked closely with V\u00e9lez and Gonz\u00e1lez to translate their vision into detailed product specifications and wireframes. This included determining what questions taxpayers would need to answer about their finances, as well as understanding tax codes. By going through this essential front-end scoping process, Tributi was able to avoid rework due to miscommunication \u2013 meaning it could launch its product faster with full confidence.</p><p id="">Using the detailed requirements and wireframes created during scoping, Airdev\u2019s development team started building the app. With everything in place, Tributi was able to sit back and wait for Airdev to provide weekly updates where they could test the product to make sure it was on track or if it needed adjustments.\u00a0\u00a0</p><p id="">Once the product launched, it received national news coverage and scaled to thousands of daily active users overnight. With Airdev\u2019s ongoing support, Tributi\u2019s tax engine successfully handled the surge.\u00a0</p>`,
    result: `<p id="">By building with Airdev, Tributi was able to hit the market in time for tax filing season, supporting 20k daily users, with a functional and well-designed product. It even became a part of Y Combinator within four months, which they wouldn\u2019t have been able to do otherwise.</p><p id="">This led to an early $800k investment in the company from <a href="https://ycombinator.com/" target="_blank">Y Combinator</a>, <a href="https://foundationcapital.com/" target="_blank">Foundation Capital</a>, and <a href="https://www.graphventures.com/" target="_blank">Graph Ventures</a> to help the startup grow. With this early product prototype built with Airdev, Tributi has since been able to hire their own engineering team in Latin America and expand the service to new countries.\u00a0</p><p id="">The company now enjoys a growing user base that mainly comes from word-of-mouth referrals. Taxpayers are able to use the online platform to file taxes for significantly less time and money than through traditional accountants, and tax accountants are able to digitize their paperwork and stay on top of constantly changing tax codes.\u00a0</p>`,
    marketplace: false,
    saas: false,
    metaTitle: "Tributi Tax Software Funded by Y-Combinator",
    publishedOn: "Thu Apr 09 2026 01:52:50 GMT+0000 (Coordinated Universal Time)",
    updatedOn: "Thu Apr 09 2026 01:49:49 GMT+0000 (Coordinated Universal Time)",
  },
];
