/**
 * Rich copy for core case studies (Convex seed).
 * `slug` values match live routes (`/case-studies/:slug` + static export list).
 */
export const CORE_CASE_STUDIES_DETAILED = [
  {
    name: "NaviGreat",
    slug: "navigreat",
    archived: false,
    draft: false,
    filteringCategory: "startups",
    businessType: "Nonprofit organization",
    productType: "Social network platform",
    timeline: "2 weeks",
    keyResults: "A fully functional app developed in just 2 weeks",
    sortOrder: 12,
    thumbnailSummary:
      "How NaviGreat built a digital hub for nonprofit organizations with Airdev's freelance Bubble developer in just 2 weeks",
    thumbnailImage:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/6644f29802eba3647e2d8030_NaviGreat_Airdev_no_code.jpg",
    heroSummary: `<p id="">After starting a nonprofit with his sister to help refugees get integrated into their new countries, NaviGreat founder Ashutosh Mishra saw an opportunity to pivot their project from on-the-ground services to a digital application that could be used in any organization.</p><p id="">However, their financial resources and timeline for developing the app were tight.<br><br><em id="">"We had a very low budget because we're working with nonprofits and humanitarian organizations. We also needed a way for it to be developed quickly because there are emergent needs and crises on hand." - Mishra&nbsp;</em>‍</p><p id="">Mishra initially explored learning Bubble to build the app himself, but soon realized the need for a professional developer due to time constraints. In February 2023, he opted for Airdev's Flex model, hiring a skilled freelance Bubble developer. </p><p>With the help of Airdev's freelance Bubble developer, NaviGreat:</p><ul id=""><li id="">Developed a fully functional app in just 2 weeks</li><li id="">Had ongoing access to a highly proficient Bubble developer on an as-needed basis for app updates and refinement </li><li id="">Fulfilled their contract with Afghan refugee groups</li></ul>`,
    quoteImage:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/6644f4ee9a20126f57e4a174_Ashutosh%20Mishra.jpeg",
    quote:
      "I went to freelancing websites and came across people who claimed they could do a lot of things, but ultimately couldn't deliver what I needed. Airdev was more expensive compared to other options, but after talking with their team and then my developer, it was really clear that this was a well-established, nicely operated firm that does this full-time and is professional. This was super important with my name and reputation on the line.",
    quoteName: "Ashutosh Mishra",
    quoteRole: "Co-founder of NaviGreat",
    objective: `<p id="">NaviGreat's purpose is to be a digital hub for organizations working with disadvantaged populations to help them achieve better social, health, and economic outcomes. Its goal is to act as a social network for communities who share a common identity or experience to organize around each other and disseminate information.</p><p id="">To facilitate this, Mishra needed the app to include the usual social network platform features and functionality, along with some custom-built elements. But most importantly, it had to be extremely user friendly and provide a lot of value to users quickly.</p><p id="">After spending a couple months trying to learn and design the app in Bubble himself, he decided to look for help.&nbsp;</p><p id=""><em id="">"I realized that doing this myself wasn't an efficient use of my time and I probably wasn't creating the best product. While I've become comfortable using Bubble, my skills aren't as advanced as someone who does this full-time. I needed an experienced person who could dedicate a lot of time and be very efficient and effective." - Mishra</em>‍</p>`,
    solution: `<p id="">After an extensive search for Bubble freelancers, Mishra came across Airdev's Flex offering, which provides access to the top 1% Bubble developers on a fractional basis, and decided to hire their expertise to build the app.&nbsp;</p><p id=""><em id="">"I went to freelancing websites and came across people who claimed they could do a lot of things, but ultimately couldn't deliver what I needed. Airdev was more expensive compared to other options, but after talking with their team and then my developer, it was really clear that this was a well-established, nicely operated firm that does this full-time and is professional. This was super important with my name and reputation on the line." - Mishra </em></p><p id="">Once matched, Mishra shared his vision and existing app design outline with his matched freelance Bubble developer. His Bubble developer then broke up the design into discrete milestones that would fit the allotted budget for that period of work.<em id="">‍</em></p><p id=""><em id="">"He made it very clear for us to know what he was going to be working on for the next period of time. And even though he's a developer, he had the project management sense to be able to break things down and help proactively plan how to do the work – instead of me having to hand him individual tasks." - Mishra</em></p><p id="">Mishra and his developer managed all tasks using the project management tool Trello.</p>`,
    result: `<p id="">Within 2 weeks (80 development hours), Airdev's freelance Bubble developer completed the app – allowing them to soft-launch with their first contracted Afghan refugee group. They're currently testing the app with a smaller user base, but will expand the app to the organization's whole community soon.&nbsp;</p><p id="">Mishra still collaborates with his Bubble developer for new app features, updates, and maintenance, but is entering a phase where he'll be able to do upkeep on his own.&nbsp;</p><p id=""><em id="">"Even though I've limited programming experience, it's enough to be able to make slight tweaks and edits and feel like I have some degree of control over the progression of the application over the long term, rather than depending on a developer that I might lose if I run out of budget. I'll still be able to run the website and that's awesome." - Mishra</em>‍</p>`,
    marketplace: false,
    saas: false,
    metaTitle: "NaviGreat Digital Hub for Nonprofit Organizations",
    publishedOn: "Mon Sep 01 2025 13:44:23 GMT+0000 (Coordinated Universal Time)",
    updatedOn: "Mon Sep 01 2025 13:44:16 GMT+0000 (Coordinated Universal Time)",
  },
  {
    name: "Playground IEP",
    slug: "playground-iep-special-ed-no-code-tool",
    archived: false,
    draft: false,
    filteringCategory: "startups",
    businessType: "Startup",
    productType: "Internal management portal",
    timeline: "3 months",
    keyResults: "5 pilot schools signed up in <1 year",
    sortOrder: 8,
    companyUrl: "https://playgroundiep.com/",
    thumbnailSummary:
      "How Airdev helped Playground IEP create a special education caseload management tool for schools",
    thumbnailImage:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/63b8851d340bdc19030b55b3_adam-winger-7fF0iei80AQ-unsplash%205.jpg",
    heroSummary: `<p id="">While serving as the director of special ed at a school on the south side of Chicago, special educator Sean Klamm was frustrated that he and his colleagues were spending so much time manually managing their caseloads through spreadsheets.</p><p id=""><em id="">"All data management is manual. The current special systems that exist aren't user friendly. We'd download raw CSV files, upload them into Google sheets, manipulate them in some crazy way, and then we'd end up with a spreadsheet that makes no sense to anybody but ourselves. Then we'd try to use these spreadsheets to communicate info to teachers, because teachers need to know basic information about students and their disabilities to better support them…we'd spend so much time doing things that weren't serving children." - CEO and founder of Playground IEP, Sean Klamm</em>‍</p><p id="">Every year Klamm found himself building his own tools to streamline this process. When he left his school, he decided to build a tool for schools that could eliminate these issues and save educators time.&nbsp;</p><p id="">After realizing how complex the data and database structure needed to be, he partnered with Airdev to develop Playground IEP, a cloud-based special education caseload management tool.</p><p id="">With the help of Airdev, he was able to:</p><ul id=""><li id="">Develop a tool that saves teachers time, increases compliance, and improves the implementation of student support in the classroom</li><li id="">Sign up 5 pilot schools on the platform in less than a year</li><li id="">Develop a 2nd platform build based on school user feedback, with a 3rd build planned</li></ul>`,
    quoteImage:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/63b8872b6c56851ed3c27f70_1667319509752.jpeg",
    quote:
      "There's a lot of security concerns and that's probably the biggest concern when talking to schools. It gives me peace of mind that the sensitive data housed on the platform is secure. And I was very happy with how Airdev went about user provisioning.",
    quoteName: "Sean Klamm",
    quoteRole: "Playground founder and CEO",
    objective: `<p id="">Klamm's goal was to automate many of the manual tasks of case management so schools could refocus their energy from spreadsheets to students. This included giving teachers a place to easily access up-to-date student information, as well as automated IEP (individualized education program) scheduling between all of a student's service providers.&nbsp;</p><p id="">To build a tool that could do this for schools he first looked to hire a development team.&nbsp;</p><p id=""><em id="">"All the startup advice I was reading told me I needed a co-founder, but I didn't know anybody so I decided to hire a team to do it. I had a conversation with a development team based in Portugal, but that didn't go anywhere. That's when I started looking for a development partner that could help me build something legitimate enough to bring to schools." - Klamm&nbsp;</em>‍</p><p id="">After exploring building the tool himself, Klamm recognized that the tool's data and database structure would need to be extremely complex.&nbsp;</p><p id="">‍</p>`,
    solution: `<p id="">After holding an initial call with Airdev to see if there might be a good working fit, Klamm decided to partner with Airdev to bring his vision to life faster with fewer challenges.&nbsp;&nbsp;</p><p id=""><em id="">"I had some hesitations with Airdev at the beginning because I was worried they wouldn't be able to structure the database how it needed to be structured. But I ended up being very pleased with Airdev's expertise. I was impressed by their ability to figure it out, because from the developers I've talked to, what I was trying to do is quite complex." - Klamm</em></p><p id="">Before jumping into development, Airdev's dedicated project manager spent 1 month in scoping to align Klamm's vision to specific features to build into the product roadmap. This included designing the right user signup and school onboarding flow, as well as correctly outlining the complex data and functionality needs in the portal for various user role capacities so Airdev's developers could quickly build with a detailed plan in hand.&nbsp;</p><p id="">Using the requirements and wireframes created during scoping, Airdev's development team started building the app. During the standard 30-day client testing phase of the app, Airdev's Customer Success Manager worked with Klamm to understand how the product would be launched to initial users, and help unpack any iterations or adjustments needed to ensure a successful roll out. By having this specialized role in place, Klamm and Airdev were able to increase communication and launch an intricate tool that could be used in any public school setting.</p><p id=""><em id="">"A lot of the requirements for the tool were to build it for the lowest common denominator of every school situation…it needed to be built for the masses. Playground is beautiful. One thing I really appreciated about Airdev is how nice their custom components look." - Klamm&nbsp;&nbsp;&nbsp;</em></p><p id="">The tool consists of 3 core time-saving features for school users:</p><ul id=""><li id=""><strong id="">IEP Snapshots:</strong> to generate easily edited and shared snapshots for each child on the caseload. Snapshots ensure that all staff have the most vital information/documents about students on the caseload.</li><li id=""><strong id="">Automated IEP Scheduling:</strong> to automatically invite every service provider attached to a student so no one is forgotten. Meeting invites automatically populate on teachers' dashboard on Playground.</li><li id=""><strong id="">Individualized Teacher Dashboards:</strong> to display all of a teacher's students so they don't have to dig through a list to find their kids on the caseload. Their dashboard also displays all IEP meetings that a teacher has been invited to. &nbsp;</li></ul>`,
    result: `<p id="">Klamm was able to bring his new tool to market in just 3 months. In less than a year, he's signed up 5 pilot schools to successfully run the tool in their special education departments. He launched a 2nd build of the tool completely based on school user feedback, and is planning a 3rd build to add Google sign-on functionality to further streamline access for schools.&nbsp;</p><p id=""><em id="">"My goal is for Playground IEP to be the premier special education software to support caseload management because the current special ed platforms aren't designed for the day-to-day internal management in a school. I'm very happy I've gone back to Airdev for the 2nd build, and I'm going back to them for the 3rd build." - Klamm</em></p><p>‍</p>`,
    galleryImages: [
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/63bf3e5300713903f494eeb3_screely-1673477613395.png",
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/63bf3e578d463f80d7b5a5e2_screely-1673477632213.png",
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/63bf3e5b9a706da8dfe59549_screely-1673477648917.png",
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/63bf3e5f19c275c9384a43db_screely-1673477662667.png",
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/63bf3e63ced9141068a611d0_screely-1673477682706.png",
    ],
    marketplace: false,
    saas: true,
    metaTitle: "Playground IEP Custom Education Tools",
    publishedOn: "Thu Apr 09 2026 01:52:50 GMT+0000 (Coordinated Universal Time)",
    updatedOn: "Thu Apr 09 2026 01:45:04 GMT+0000 (Coordinated Universal Time)",
  },
  {
    name: "Cerebro Sports",
    slug: "cerebro-sports-analytics-platform-no-code",
    archived: false,
    draft: false,
    filteringCategory: "startups",
    businessType: "Startup",
    productType: "Analytics Platform",
    timeline: "2 months",
    keyResults:
      "A pre-seed fundraising round led by Mark Cuban to help scale internal data operations",
    sortOrder: 10,
    companyUrl: "https://www.cerebrosports.com/",
    thumbnailSummary:
      "How a Mark Cuban-funded startup upgraded spreadsheets to a scaling product with Airdev",
    thumbnailImage:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/64eced7d1af330bc878905e9_Cerebro_Airdev_no_code-app-build.jpg",
    customerLogo:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/64ecedcd33fbce5f76e1ccf4_Cerebro-Sports-Horizontal-Logo-260W-Main.webp",
    heroSummary: `<p id="">For many high school and college basketball players, getting onto the radar of a college or NBA team is a struggle. There are scouts on the ground relaying player info to schools and teams, however they rely on the eye test – meaning many good players go overlooked.</p><p id="">But what if there was another fairer way to tell a full, objective story of player performance in the basketball industry that replaces hype with data-driven analytics? That's the idea behind Cerebro Sports, a SportsTech startup with a player evaluation platform that maintains a global database of basketball performance analytics so that players are able to better track their individual development and coaches can more efficiently and cost-effectively evaluate prospects.</p><p id="">With the help of Airdev, Cerebro Sports was able to:</p><ul id=""><li id="">Develop a working beta version of the platform in just two months, along with multiple product iterations</li><li id="">Add 600k+ player records on the platform in two years</li><li id="">Establish a growing user base of college programs, pro teams, agencies, media, players, fans, and other key stakeholders in the basketball ecosystem</li><li id="">Expand operations with an investment by entrepreneur and NBA governor Mark Cuban</li></ul>`,
    quoteImage:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/64ecef0fc2aaa629ab933cef_Ed%20Chao_Cerebro%20Sport.jpeg",
    quote: `We hosted two focus groups on our MVP in Google Sheets for college coaches that Hall of Fame Legend Coach (and investor) John Beilein helped us organize. They thought it was cool. But after we built our platform and showed the coaches, one of them said, 'You can do all of that on this one platform? This is the future of recruiting'.`,
    quoteName: "Ed Chao",
    quoteRole: "Co-Founder & VP of Operations at Cerebro Sports",
    objective: `<p id="">The founders of Cerebro saw the need for decision makers and players/prospects to have better insights and more objective data during the recruiting process. Their idea was to make a database product that creates profiles for players and attaches all of their records to one unique identifier.&nbsp;</p><p id=""><em id="">"Our hope was to help these kids get recruited to colleges, get scholarships, and to be able to provide data that shows the proof that they are at the level to get into certain college programs. We wanted to even the playing space for these kids so that they had a fair fight at scholarship opportunities and positions on those teams." - Rohan Dang, Co-founder &amp; VP of Strategy at Cerebro.</em>‍</p><p id="">They started by creating a fully functional MVP dashboard in Google Sheets, but they needed something that would scale.&nbsp;</p>`,
    solution: `<p id="">To convert their system of Google Sheets into a web app where they could start building their product, Cerebro's founders explored development options that could get them to market quickly and cost-effectively.</p><p id=""><em id="">"I don't think we were ever going to consider the traditional development approach because of the high expenses. That's why we sought out Airdev. As we started initial conversations with the Airdev team, they seemed really confident that they were going to be able to knock out exactly what we needed. And that's exactly what happened." - Rohan Dang</em>‍</p><p id="">Cerebro began working with Airdev and was able to spin out the first version of the product in just two months.</p><p id="">Right away, Cerebro gave Airdev their Google Sheets which provided the blueprints for the platform. These showed how the data was related and flowed, where the formulas were coming from, and what they wanted their dashboards to look like. Using these blueprints, Airdev's dedicated Product Manager worked closely with Cerebro to translate their vision into detailed product specifications and wireframes, which were then passed to the development team to build the app.</p><p id=""><em id="">"I've really enjoyed working with the developers and designers on their team. The programmer we worked with was so responsive, addressing new ideas of issues right away – even when I was working at 2am – and having that was amazing." - John Cho, Co-founder &amp; Chief Product Officer at Cerebro.</em>‍</p><p id="">In the end, Airdev was able to provide Cerebro with an easy-to-access, scalable app that does the following:</p><ul id=""><li id="">Allows individual players to monitor their game performance while simultaneously comparing with competitors across the country</li><li id="">Provides coaches with aggregated player data in a consolidated platform where recruiting programs can zoom in on specific players or filter by skill categories, allowing thorough player evaluations in under 60-seconds</li></ul>`,
    result: `<p id="">By building with Airdev, Cerebro was able to accelerate its public view and quickly gain market share in a tough-to-break-through environment (coaches have been operating the same workflows for 20+ years). In addition, they've been able to iterate on the product multiple times, including the addition of a new portal and a full database restructuring.</p><p id=""><em id="">"My initial worry was that we'd outgrow the system. But I've been pleasantly surprised. We started with a few smaller ideas and formulated our entire web app just around trying to serve that specific audience and product. Then over time, we've iterated so many different times to create essentially a brand new product from what we started with. And it's always been rather seamless to get from one step to the next." - Rohan Dang</em>‍</p><p id="">All of this has led to a <a href="https://www.sportsbusinessjournal.com/Daily/Issues/2022/09/22/Technology/dallas-mavericks-mark-cuban-funding-round-cerebro-sports-basketball-analytics.aspx" target="_blank">pre-seed fundraising round, led by Mark Cuban</a>, which will help scale internal data operations, while allowing Cerebro to grow its institutional client base and prepare for the release of a consumer offering.</p><p id="">‍</p>`,
    marketplace: false,
    saas: false,
    metaTitle: "Cerebro Sports Scaled Spreadsheets to a Platform",
    publishedOn: "Thu Apr 09 2026 01:52:50 GMT+0000 (Coordinated Universal Time)",
    updatedOn: "Thu Apr 09 2026 01:37:24 GMT+0000 (Coordinated Universal Time)",
  },
  {
    name: "Dividend Finance",
    slug: "dividend-finance-fintech-mvp-product",
    archived: false,
    draft: false,
    filteringCategory: "enterprises",
    businessType: "Enterprise",
    productType: "FinTech MVP",
    timeline: "6 weeks",
    keyResults: "Billions of dollars of loans processed",
    sortOrder: 1,
    companyUrl: "https://www.dividendfinance.com/",
    thumbnailSummary:
      "How we built a FinTech platform for Dividend Finance that scaled to process billions of dollars of loans",
    thumbnailImage:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/635075842347dc61d12ccf06_dividend%20(1).jpeg",
    videoLink: "https://www.youtube.com/watch?v=52AlBlnB04c",
    customerLogo:
      "https://e47b698e59208764aee00d1d8e14313c.cdn.bubble.io/f1766447523324x536489976697318800/dividend.png",
    heroSummary: `<p id="">Today, Dividend Finance is a leading national provider of renewable energy and energy-efficient financing solutions to property owners.</p><p id="">But in 2014, it was a startup trying to get its digital platform off the ground. It had started building an original product using a team of traditional software developers. However, after 6 months of development, Dividend had spent much of its budget and still didn't have a viable product.</p><p id="">Feeling the pressure from burning a lot of time and cash on a solution that wasn't working, Dividend changed course. It partnered with Airdev to launch a minimum viable product (MVP) of the platform using the no-code tool Bubble – in just 6 weeks.</p><p id="">As a result:</p><ul id=""><li id="">Billions of dollars of loans have now been processed through the app</li><li id="">Tens of thousands of reps interact with the system every day</li><li id="">Hundreds of millions of dollars in equity financing have been raised</li></ul>`,
    quoteImage:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/62aa5d924f4516be80155a2b_phil.jpeg",
    quote: `Airdev has been absolutely instrumental in our company…As a startup, your pace and speed to market is absolutely crucial. For us, the ability to get things done quickly is something that we've focused on, and that's one of the main reasons that we've been successful. It's because Airdev was able to come in and match our goals and rapid pace that we're trying to hit with development.`,
    quoteName: "Phil M.",
    quoteRole: "SVP, Head of Product at Dividend Finance",
    objective: `<p id="">Dividend needed to get a working platform up and running fast to successfully run its business. This meant serving multiple stakeholders, such as borrowers, solar installers, investors, and internal employees, with a platform that could do the following:&nbsp;</p><ul id=""><li id="">Perform credit checks on potential borrowers and provide decision logic&nbsp;</li><li id="">Generate complex, custom proposals for borrowers based on variety of personalized factors</li><li id="">Integrate tightly with Salesforce&nbsp;</li><li id="">Populate and calculate new data at each step of a project</li><li id="">Integrate with meter providers to track the amount of solar energy generated by the installed solar panels</li><li id="">Track loan repayment history</li></ul><p id="">Unfortunately, its traditionally coded app was not yet close to meeting these requirements in the required timeframe.</p>`,
    solution: `<p id="">Unable to continue investing significant time and money indefinitely, Dividend sought a new approach. Its chief technology officer was familiar with the no-code tool Bubble and suggested it as an alternative route to get their MVP live. Feeling the pressure, Dividend decided to give this more unconventional option a shot.</p><p id="">Their team didn't have any Bubble experts on staff, so they hired Airdev to do the initial product build.&nbsp;</p><p id=""><em id="">"Without Airdev, we wouldn't have been able to develop that core product nearly as quickly as we have. We went within the course of only a few months from an idea with no platform at all to having dozens of contractors who were actually working and utilizing our platform." - Phil M.</em></p><p id="">With an understanding that Dividend needed a working product with complex functionality fast, Airdev's development team got started building a fully functional MVP in just 6 weeks.&nbsp;</p><p id="">Airdev worked closely with Dividend to align on the highest-impact features and formalize the project's scope and designs to hit specific timelines. The goal was to build Dividend a fintech application that it could continue to use and scale beyond the initial build. This was made possible by fully integrating the first version of the application with Salesforce so that Dividend could continue to facilitate key operational functionality, like contract generation and charging customers' bank accounts.&nbsp;</p><p id=""><em id="">"Airdev is a great solution for companies who are starting at the very earliest stage, who are trying to come up with a proof of concept…But, [they're] not just for the brand new ideation and MVP types. Airdev has built a system that's enabled us to scale as well." - Phil M.</em></p>`,
    result: `<p id="">Since the initial build, the app has grown substantially in size, complexity, and the number of transactions that it supports. Today, the platform has processed billions of dollars in loan volume and serves tens of thousands of users.&nbsp;</p><p id="">By developing with no-code, Dividend was even able to improve its business strategy. It wanted to be known as a company that was super-responsive to its customers' requests for features. With no-code, it could release new features, sometimes on a weekly basis, because it could move quickly on the development front.&nbsp;</p><p id="">As the company matured, it eventually hired an in-house software development team to build some of the business logic in code. For example, the Bubble application was re-engineered to integrate through API calls with the new, code-based part of the application. In addition, the following complex requirements were added:</p><ul id=""><li id="">Ability for external stakeholders to plug into the application's API</li><li id="">SSO integrations with other system, such as a learning management system (LMS)&nbsp;</li><li id="">A more robust proposal generation process with more complex configuration options</li></ul><p id="">With Airdev's help, Dividend Finance was able to build an MVP in one month that evolved and scaled with its own growth and needs.</p>`,
    marketplace: false,
    saas: true,
    metaTitle: "Dividend Finance Scales No-Code Loan Platform",
    publishedOn: "Mon Dec 15 2025 22:13:20 GMT+0000 (Coordinated Universal Time)",
    updatedOn: "Mon Dec 08 2025 22:13:08 GMT+0000 (Coordinated Universal Time)",
  },
  {
    name: "Cadence Translate",
    slug: "cadence-translate-internal-tool-salesforce",
    archived: false,
    draft: false,
    filteringCategory: "enterprises",
    businessType: "SMB",
    productType: "Salesforce-integrated gig management platform",
    timeline: "4 weeks of development",
    keyResults: "400% increase in jobs processed per month",
    sortOrder: 4,
    companyUrl: "https://www.cadencetranslate.com/",
    thumbnailSummary:
      "How Airdev helped Cadence Translate connect Salesforce data to a custom gig portal in just weeks",
    thumbnailImage:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/635075508b8a7df25b80e904_cadence%20(1).jpeg",
    videoLink: "https://www.youtube.com/watch?v=yUGK2RKRm-E&t=2s",
    customerLogo:
      "https://cdn.prod.website-files.com/62aa5d914f4516fb36155657/669a9ff1b72d8c1ec14d79f4_cadence.webp",
    heroSummary: `<p id="">Cadence Translate is a leading provider of language services to the global business and investment community.</p><p id="">Founded with the goal to connect the private sector with world-class translators, Cadence Translate experienced rapid growth over a short period of time. It had reached 2,500 professional linguists and realized that Salesforce's per-seat cost model would become too burdensome at scale.</p><p id="">To find a more growth-friendly alternative, Cadence partnered with Airdev to reduce stress and cost by connecting Salesforce data to a custom gig portal for thousands of its expert translators.</p><p id="">With the help of Airdev, Cadence was able to:</p><ul id=""><li id="">Process 400% more jobs per month</li><li id="">Grow company revenue by 3x</li><li id="">Increase the lifespan of relationships with interpreters and clients</li></ul>`,
    quoteImage:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/633744a720ddae6ab53aa762_download.jpg",
    quote: `In just weeks, Airdev created an elegantly streamlined version of our previous gig management platform, built on top of our Salesforce data. The result became an instant hit with our network of linguists, while dramatically reducing the time we spend on ongoing maintenance.`,
    quoteName: "Matt Conger",
    quoteRole: "CEO and Founder of Cadence",
    objective: `<p id="">Cadence's goal was simple. It needed a system that could scale to thousands of users around the world without financially harming the business. This system needed to allow its account managers — the backbone of the operation — to efficiently do the following:</p><ul id=""><li id="">Look over many different interpreter profiles&nbsp;</li><li id="">Notify and query the interpreters about a job</li><li id="">Present the selected interpreter to the client in a credible way&nbsp;</li></ul><p id="">Unfortunately, its existing platform, Salesforce, was too expensive to grow with this need.</p>`,
    solution: `<p id="">Cadence partnered with Airdev to build a custom gig portal. This platform took the underlying structure of Salesforce's data and connected it to a lightweight web app that could scale to thousands of different users without any additional per-user cost.</p><p id="">Defining the scope of work is the critical first step of any software project. To assist this process, Airdev assigned Cadence a dedicated Product Manager to work closely with its key stakeholders and translate its needs into a detailed scope doc with product descriptions and wireframes. This allowed Airdev and Cadence to fully align on the product's functionality and definition of success so that Airdev's development team could confidently hit every deadline.</p><p id="">Throughout the build, Cadence was able to review progress with its Product Manager and provide feedback. This ensured everything went according to plan and the platform launched ready to meet the objectives in just weeks.&nbsp;</p><p id="">‍</p>`,
    result: `<p id="">Cadence immediately felt the benefits of its new Salesforce-integrated portal. Before building an app with Airdev, its staff could only process around 80 interpreter jobs per month. After the new gig portal launched, Cadence grew its capacity to process around 400 jobs per month. With this new ability to manage so much more at scale, Cadence's revenue tripled.&nbsp;</p><p id="">‍<em id="">"This wouldn't have been possible without Airdev and their commitment to building a system that scaled specifically for our needs…It really helped us go from using Salesforce as an internal-only tool to something that all users across the world could log into and be perfectly in-synch." - Matt Conger</em></p><p id="">‍</p>`,
    marketplace: false,
    saas: false,
    metaTitle: "Cadence Translate Salesforce Custom Integration",
    publishedOn: "Thu Apr 09 2026 01:52:50 GMT+0000 (Coordinated Universal Time)",
    updatedOn: "Thu Apr 09 2026 01:47:34 GMT+0000 (Coordinated Universal Time)",
  },
  {
    name: "Bubble.io",
    slug: "bubble-io-developer-certification-exam-rebuild",
    archived: false,
    draft: false,
    filteringCategory: "enterprises",
    businessType: "SMB",
    productType: "Exam platform",
    timeline: "3 months",
    keyResults:
      "A more performant, reliable, and flexible exam for users and internal developers",
    sortOrder: 0,
    companyUrl:
      "https://bubble.io/blog/developer-certification-bubble-app/",
    thumbnailSummary:
      "How no-code leader Bubble turned to Airdev for a custom rebuild of their Developer Certification Platform... built on Bubble",
    thumbnailImage:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/665f5ab8b085585d4543d3ea_Certification---In-line-5.png",
    customerLogo:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/665f59210e5f3d1400962c7f_bubble%20logo.png",
    heroSummary: `<p id="">After over a decade as the world's leading no-code platform, the team at Bubble decided to try something new: hiring one of their own agencies to completely rebuild their <a id="" href="http://bubble.io/certification" target="_blank">developer certification platform</a> using Bubble.</p><p id="">With their internal team at capacity with other projects, Bubble released <a id="" href="https://bubble.io/hire-a-developer" target="_blank">an RFP</a> in early 2024 to find an external agency partner to help rebuild their Bubble Developer Certification exam. After evaluating proposals from 8 different Gold agency partners, they decided to partner with Airdev for the project.</p><p id="">With Airdev's help, Bubble was able to:</p><ul id=""><li id="">Rebuild the new exam platform in just 3 months – done without taking the exam offline</li><li id="">Develop a more reliable and polished exam with a noticeably better user experience&nbsp;</li><li id="">Improve platform flexibility, enabling continuous enhancements and iterations without user disruption</li></ul>`,
    quoteImage:
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/665f5dde1301ef0955923d8b_Emmanuel%20Straschnov_Bubble.io.jpeg",
    quote: `Airdev is the oldest and largest Bubble agency with experience in building enterprise-grade applications. We needed a team we could trust to build our certification platform in a secure and performant way, so working with Airdev was an easy decision.`,
    quoteName: "Emmanuel Straschnov",
    quoteRole: "Co-CEO of Bubble",
    objective: `<p id="">When Bubble launched its <a href="https://bubble.io/blog/developer-certification/" target="_blank">Bubble Developer Certification exam in July 2023</a>, their aim was to establish a rigorous, universal standard for professional Bubble Developers. This was a critical step to bring credibility and transparency to the no-code market and to show who is proficient at Bubble.</p><p id="">But despite the positive reception from professional Bubble Developers and employers looking to hire them, they had to address numerous issues with the third-party platform that hosted the exam, including UX problems, exam crashes, and administrative and data reporting frustrations.</p><p id=""><em id="">"We couldn't get it wrong. If the exam isn't administered well, then nobody will know who's truly proficient and that's damaging to the overall ecosystem. The software we were using kind of worked, but we needed more control for efficient bug fixes and feature integrations. That's when we realized that if we wanted our certification to become the reputable program we envisioned, we needed to custom-build it on Bubble." - Jeremy Alexander, Bubble Education Team</em>‍</p>`,
    solution: `<p id="">Once the decision to rebuild was made, Bubble knew they wanted to move quickly. However, all of their in-house Bubble Developers were already allocated to other prioritized projects.&nbsp;</p><p id=""><em id="">"This is when we realized we have all these agencies building on Bubble, we have an RFP system, we might as well 'eat our own dog food' and use it." - Alexander</em>‍</p><p id="">To keep the project moving forward, Bubble created an RFP to find a partner for their project. They shared a detailed scope of work with potential agencies and were clear about the budget.&nbsp;</p><p id=""><em id="">"We received 8 proposals from Gold agency partners and spoke to each of them. What really stood out about Airdev was just how much they understood what we were looking for. As we discussed the project details, they accurately interpreted and explained how they would build it, which aligned with how we would have done it in-house. This clarity was key in our decision to hire Airdev." - Alexander</em>‍</p><p id="">In early 2024, Bubble and Airdev swiftly began working towards a 3-month launch goal. Airdev's project manager addressed Bubble's frontend and backend functionality needs, offering new feature/UX ideas based on prior quiz and form app experience. Having taken the Bubble Developer Certification exam themselves, Airdev also drew on firsthand experience to create the best exam possible for certifying Bubblers.&nbsp;</p><p id=""><em id="">"This project was especially meaningful to us. We've spent the last decade intentionally building a distinctive Bubble agency and pushing the boundaries of what Bubble can do, so it meant a lot for Bubble to trust us to build this platform. It was also gratifying to create something that brings transparency and trust to the Bubble ecosystem, and to give Bubblers the testing experience they deserve." - Andrew Haller, Co-founder and co-CEO of Airdev</em>‍</p><p id="">Within 4 days, Airdev turned these requirements and ideas into detailed mockups and weekly development plans, kickstarting the build process.</p><p id=""><em id="">"I could tell Airdev knew what it was doing and could deliver quickly. But beyond that, I could trust everything would be handled smoothly. They provided detailed insights on integrating with our existing app and infrastructure, and held weekly update meetings that included recordings to keep us informed. The process couldn't have gone smoother. Any issues that arose were quickly addressed by their team." - Alexander</em>‍</p>`,
    result: `<p id="">In just 3 months, Airdev helped Bubble totally rebuild and launch their new Bubble Developer Certification exam experience – entirely on their own platform. The new application provides exam takers with a much more performant, reliable, and flexible experience, most importantly reducing the exam crash rate from 5% to zero.&nbsp;</p><p id=""><em id="">"People who saw both platforms immediately noticed the improvement. The new experience is vastly better, offering more control and visibility for new developers. Feedback has been very positive, with everyone excited about the new platform's look and feel. It integrates well with our current styling, unlike the old platform, giving us a solid foundation for future development." - Alexander</em>‍</p><p id="">And for Bubble's education team, who previously lacked the tools to improve the exam iteratively and quickly, they can now continuously add questions without disrupting current test-takers, further enhancing the quality of the exam and better supporting the entire no-code ecosystem. Read more about their experience on the <a href="https://bubble.io/blog/developer-certification-bubble-app/" target="_blank">Bubble blog</a>.&nbsp;</p>`,
    galleryImages: [
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/665f5ab8b085585d4543d3ea_Certification---In-line-5.png",
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/665f5abe2c04a22a1e388d31_Certification---In-line-3-7.png",
      "https://cdn.prod.website-files.com/62aa5d914f45160a7f155660/665f5ac430526eff2b4c4b99_Certification---In-line-4-1.png",
    ],
    marketplace: false,
    saas: true,
    metaTitle: "How Airdev Rebuilt the Bubble Certification Exam",
    publishedOn: "Mon Sep 01 2025 14:29:23 GMT+0000 (Coordinated Universal Time)",
    updatedOn: "Mon Sep 01 2025 14:29:16 GMT+0000 (Coordinated Universal Time)",
  },
];
