import {
  BanknotesIcon,
  CreditCardIcon,
  ChartBarIcon,
  CalculatorIcon,
  ShieldCheckIcon,
  BuildingLibraryIcon,
  DocumentTextIcon,
  UserGroupIcon,
  GlobeAltIcon,
  BellIcon,
  ClockIcon,
  CurrencyDollarIcon,
  ArrowPathIcon,
  FolderIcon,
  ScaleIcon,
  DocumentCheckIcon,
  ChatBubbleLeftRightIcon,
  PresentationChartLineIcon,
  ChartPieIcon,
  IdentificationIcon,
} from "@heroicons/react/24/solid";
import { Product } from "./sample-products";

export const FINTECH_PRODUCTS: Product[] = [
  {
    id: "lending-credit",
    name: "Lending & Credit",
    subtitle: "Platforms for originating, underwriting, and servicing loans",
    description: "Consumer lending, commercial finance, BNPL, and specialty credit products. These systems handle everything from application intake to repayment tracking, with the integrations and compliance workflows the space requires.",
    icon: BanknotesIcon,
    color: "#10b981",
    features: [
      { name: "Loan application and intake flows", icon: DocumentTextIcon },
      { name: "Credit decisioning and underwriting logic", icon: ScaleIcon },
      { name: "Document collection and verification", icon: DocumentCheckIcon },
      { name: "Loan servicing and payment tracking", icon: ClockIcon },
      { name: "Integration with credit bureaus and data providers", icon: GlobeAltIcon },
      { name: "Compliance and audit logging", icon: ShieldCheckIcon },
    ],
  },
  {
    id: "payments-transactions",
    name: "Payments & Transactions",
    description: "Software for moving money. Payment processing platforms, virtual card programs, expense management tools, and transaction monitoring systems. Products that integrate with the major payment rails and card issuers to handle real money at scale.",
    icon: CreditCardIcon,
    color: "#6366f1",
    features: [
      { name: "Payment gateway integration (Stripe, Marqeta, Plaid)", icon: GlobeAltIcon },
      { name: "Virtual and physical card issuance", icon: CreditCardIcon },
      { name: "Transaction monitoring and alerts", icon: BellIcon },
      { name: "Multi-currency and FX support", icon: CurrencyDollarIcon },
      { name: "Reconciliation and settlement workflows", icon: ArrowPathIcon },
      { name: "PCI-compliant architecture", icon: ShieldCheckIcon },
    ],
  },
  {
    id: "wealth-portfolio",
    name: "Wealth & Portfolio Management",
    description: "Tools for managing investments and tracking portfolios. Advisor platforms, self-service investment dashboards, and products that aggregate financial data, display performance, and help users make informed decisions about their money.",
    icon: ChartBarIcon,
    color: "#8b5cf6",
    features: [
      { name: "Portfolio tracking and performance reporting", icon: PresentationChartLineIcon },
      { name: "Account aggregation via Plaid, Yodlee, etc.", icon: GlobeAltIcon },
      { name: "Investment analytics and benchmarking", icon: ChartPieIcon },
      { name: "Client reporting and statements", icon: DocumentTextIcon },
      { name: "Model portfolio management", icon: FolderIcon },
      { name: "Advisor and client portals", icon: UserGroupIcon },
    ],
  },
  {
    id: "tax-accounting",
    name: "Tax & Accounting",
    description: "Software for managing tax obligations, filings, and financial record-keeping. Tax preparation platforms, accounting tools, and compliance systems that handle complex calculations and reporting requirements.",
    icon: CalculatorIcon,
    color: "#f59e0b",
    features: [
      { name: "Tax calculation engines", icon: CalculatorIcon },
      { name: "Document upload and organization", icon: FolderIcon },
      { name: "E-filing integrations", icon: GlobeAltIcon },
      { name: "Multi-entity and jurisdiction support", icon: BuildingLibraryIcon },
      { name: "Audit trail and compliance logging", icon: ShieldCheckIcon },
      { name: "Client portals and collaboration tools", icon: ChatBubbleLeftRightIcon },
    ],
  },
  {
    id: "insurance-risk",
    name: "Insurance & Risk",
    description: "Platforms for insurance distribution, policy management, and risk assessment. Tools for carriers, MGAs, and insurtechs that need to quote, bind, and manage policies while integrating with the broader insurance ecosystem.",
    icon: ShieldCheckIcon,
    color: "#ef4444",
    features: [
      { name: "Quote and bind workflows", icon: DocumentCheckIcon },
      { name: "Policy administration systems", icon: FolderIcon },
      { name: "Claims intake and tracking", icon: ClockIcon },
      { name: "Underwriting rule engines", icon: ScaleIcon },
      { name: "Integration with carriers and reinsurers", icon: GlobeAltIcon },
      { name: "Agent and customer portals", icon: UserGroupIcon },
    ],
  },
  {
    id: "banking-account",
    name: "Banking & Account Management",
    description: "Core banking interfaces, neobank products, and account management tools. Customer-facing layers that sit on top of banking-as-a-service providers, handling onboarding, account management, and day-to-day banking experiences.",
    icon: BuildingLibraryIcon,
    color: "#0ea5e9",
    features: [
      { name: "Account opening and KYC/KYB flows", icon: IdentificationIcon },
      { name: "Account dashboards and transaction history", icon: PresentationChartLineIcon },
      { name: "Fund transfers and ACH integration", icon: ArrowPathIcon },
      { name: "Debit card management", icon: CreditCardIcon },
      { name: "Notifications and alerts", icon: BellIcon },
      { name: "Integration with BaaS providers (Unit, Treasury Prime, etc.)", icon: GlobeAltIcon },
    ],
  },
];
