// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsrtiatteejgwuafavci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impqb2V2eXhheWppZmd5Y3BoeGR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MDcyNDcsImV4cCI6MjA3MjM4MzI0N30.KS2FypK3kuF3PEqMnx0tOu-oYHMGKFml_hNhHCX3m8g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});